### ISSUE TITLE
Simplify disabling Pod AntiAffinity

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1005]
### What would you like to be added?

The current Helm chart defaults to using anti-affinity rules to prevent Redpanda brokers from being colocated on k8s nodes. For users looking to purposely run Redpanda brokers on the same k8s node, such as during dev/test, they have to go out of their way setting things like:

```yaml
statefulset:
  podAntiAffinity:
    type: custom
    custom: {}
```

(If the above even works.)

Maybe we should adopt the `enable: <bool>` convention for allowing easier "disabling" of anti-affinity altogether like we do with other features in the Helm chart? This would make it explicit vs. implicit like:

```yaml
statefulset:
  podAntiAffinity:
    enabled: false
```

### Why is this needed?

See internal Slack convo: https://redpandadata.slack.com/archives/C01H6JRQX1S/p1706887665790999
