### ISSUE TITLE
Redpanda chart with issuerRef creates unused issuers referring nonexistent secrets

### ISSUE THREAD

**Issue by phooijenga** [redpanda-data/helm-charts#1011]
### What happened?

We are using the Redpanda chart with custom certificate issuers for a `default` and `external` cert.
When applied, this results in four certificates:

```
NAME                                  READY   SECRET                                AGE
redpanda-external-root-certificate    False   redpanda-external-root-certificate    62m
redpanda-default-root-certificate     False   redpanda-default-root-certificate     62m
redpanda-default-cert                 True    redpanda-default-cert                 62m
redpanda-external-cert                True    redpanda-external-cert                62m
```

The `redpanda-default-root-certificate` and `redpanda-external-root-certificate` refer to issuers that are also created by the chart, which refer to a secret which is not created.

```
NAME                            READY   STATUS                                                                                        AGE
redpanda-external-root-issuer   False   Error getting keypair for CA issuer: secrets "redpanda-external-root-certificate" not found   63m
redpanda-default-root-issuer    False   Error getting keypair for CA issuer: secrets "redpanda-default-root-certificate" not found    63m
```

As far as I can tell, these certificates are not used, the Redpanda cluster starts successfully.

### What did you expect to happen?

I did not expect these two "extra" certificates and issuers to be created.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```yaml
statefulset:
  replicas: 1
config:
  node:
    developer_mode: true
tls:
  enabled: true
  certs:
    default:
      issuerRef:
        name: internal-ca-issuer
        kind: ClusterIssuer
    external:
      issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
```
</details>

### Chart Version(s)

<details>

```console
$ helm -n infra list 
NAME         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART              	APP VERSION
redpanda     	infra    	1       	2024-02-06 14:45:47.23245 +0100 CET 	deployed	redpanda-5.7.22    	v23.3.4
```

</details>

### Cloud provider

N/A

JIRA Link: [K8S-98](https://redpandadata.atlassian.net/browse/K8S-98)

[K8S-98]: https://redpandadata.atlassian.net/browse/K8S-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
