### ISSUE TITLE
Incorrect Datatype set for redpanda podAntiAffinity

### ISSUE THREAD

**Issue by autolisis** [redpanda-data/helm-charts#1027]
### What happened?

According to helm values documentation:
```yaml
statefulset:
  # -- Anti-affinity rules for scheduling Pods of this StatefulSet.
  # For details,
  # see the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity).
  # You may either edit the default settings for anti-affinity rules,
  # or specify new anti-affinity rules to use instead of the defaults.
  podAntiAffinity:
    # -- The topologyKey to be used.
    # Can be used to spread across different nodes, AZs, regions etc.
    topologyKey: kubernetes.io/hostname
    # -- Valid anti-affinity types are `soft`, `hard`, or `custom`.
    # Use `custom` if you want to supply your own anti-affinity rules in the `podAntiAffinity.custom` object.
    type: hard
    # -- Weight for `soft` anti-affinity rules.
    # Does not apply to other anti-affinity types.
    weight: 100
    # -- Change `podAntiAffinity.type` to `custom` and provide your own podAntiAffinity rules here.
    custom: {}
```

However, trying to do helm install with the above values yaml file FAILS!
```sh
helm install -n redpanda redpanda redpanda/redpanda -f ansible/project/roles/redpanda/templates/helm-values.yaml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector): unknown field "app.kubernetes.io/component" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector, ValidationError(StatefulSet.spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector): unknown field "app.kubernetes.io/instance" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector, ValidationError(StatefulSet.spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector): unknown field "app.kubernetes.io/name" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector]
```

It has to be forced to install with 
```
helm install -n redpanda redpanda --disable-openapi-validation redpanda/redpanda -f ansible/project/roles/redpanda/templates/helm-values.yaml
```

This works fine after that.

### What did you expect to happen?

Installation should work with the helm chart documented way of configuring podAntiAffinity.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```
As mentioned above, try to modify and deploy with statefulset antiaffinityrules.
</details>

### Anything else we need to know?

<img width="1033" alt="image" src="https://github.com/redpanda-data/helm-charts/assets/25099244/f6f205fa-0b4b-4fbf-a7a3-31c874c1c8b5">

The documentation is incorrect here https://docs.redpanda.com/current/reference/k-crd/#k8s-api-github-com-redpanda-data-redpanda-operator-src-go-k8s-api-redpanda-v1alpha1-statefulset

It is mentioning that the field statefulset.pod(Anti)Affinity is of the original K8S type Pod(Anti)AffinityV1Core which it is not!

There seems to be some mismatch between the validation code and the implementation code which is resulting in the documentation as well.

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
redpanda        redpanda        1               2024-02-14 03:55:28.152387625 +0100 CET deployed        redpanda-5.7.23 v23.3.4    
```
</details>

### Cloud provider

<details>
onprem
</details>
