### ISSUE TITLE
External Ports configured in StatefulSet even if disabled

### ISSUE THREAD

**Issue by may-cDev** [redpanda-data/helm-charts#1029]
### What happened?

The following configurations are set in the values.yaml to prevent that ports are exposed externally:

```
external:
  service:
    enabled: false
  enabled: false

listeners:
  admin:
    external:
      default:
        enabled: false
```

When templating the helm chart the StatefulSet nevertheless still configures the admin-default port for the redpanda container. 
```
ports:
- name: admin
  containerPort: 9644
- name: admin-default
  containerPort: 9645
```

The same happens for the other listeners as well.

### What did you expect to happen?

Expected that the external listeners which are not needed are not configured as ports for the redpanda container in the StatefulSet

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

external:
  service:
    enabled: false
  enabled: false

listeners:
  admin:
    external:
      default:
        enabled: false

</details>

### Anything else we need to know?

The problem is probably line 286 in redpanda/templates/statefulset.yaml:

```
{{- if $external.port }}
```

This should probably be something like:
```
{{- if or ($external.enabled) (dig "externalDns" "enabled" true $values.external) }}
```

### Chart Version(s)

<details>

5.7.23

</details>

### Cloud provider

<details>
Azure
</details>
