### ISSUE TITLE
Allow specifying scheduling constraints for non-broker deployments (e.g. Console)

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1040]
### What would you like to be added?

The Helm chart should be extended to support specifying things like node selectors for non-broker services, like Console and KMinion. Currently, it's assumed all services inherit any affinity and node selector settings from the Redpanda chart.

### Why is this needed?

A user deploying Redpanda via Helm was trying to separate Console from the broker cluster. Currently, there's no way to have Console's Deployment be assigned to a specific (or non-Broker) node pool. Ideally, I'd be able to specify affinity/anti-affinity and/or node selectors for the optional services separate from the brokers.

**Comment by voutilad** [comment]
For now, as a workaround if someone is looking for one, you can patch things like the Console deployment and assign affinity and anti-affinity rules as needed. In my case, I have 2 node pools: one annotated with `role=omb` and another with `role=broker`. I have Redpanda running on the `role=broker` nodes and can patch the Console deployment like so:

1. Create a patch file (`patch.yaml`):

```yaml
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values: [ "broker" ]
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: [ "omb" ]
```
2. Patch the deployment (my namespace is `redpanda`):
```
$ kubectl patch deployment redpanda-console -n redpanda --patch-file patch.yaml
```
3. Scale the deployment to 0 to unschedule the pod(s):
```
$ kubectl scale deployment redpanda-console -n redpanda --replicas=0
```
4. Scale back up:
```
$ kubectl scale deployment redpanda-console -n redpanda --replicas=1
```
5. Verify the pod location using `kubectl`:
```
$ kubectl get pods -n redpanda -o wide
NAME                               READY   STATUS      RESTARTS   AGE    IP            NODE                               NOMINATED NODE   READINESS GATES
redpanda-0                         2/2     Running     0          35m    10.244.5.13   aks-redpanda-21508769-vmss000000   <none>           <none>
redpanda-1                         2/2     Running     0          35m    10.244.3.16   aks-redpanda-21508769-vmss000002   <none>           <none>
redpanda-2                         2/2     Running     0          35m    10.244.4.13   aks-redpanda-21508769-vmss000001   <none>           <none>
redpanda-configuration-k7cqn       0/1     Completed   0          35m    10.244.6.11   aks-omb-13292060-vmss000000        <none>           <none>
redpanda-console-7b5c8db58-z2zgb   1/1     Running     0          5m1s   10.244.7.9    aks-omb-13292060-vmss000002        <none>           <none>
```
