### ISSUE TITLE
Consider prefixing charts (redpanda-operator, redpanda-console, ...) to avoid conflicts

### ISSUE THREAD

**Issue by jdonzallaz** [redpanda-data/helm-charts#1049]
### What happened?

Because the name "operator" is so generic and also used by others (e.g. [minio](https://github.com/minio/operator/blob/master/helm/operator/Chart.yaml)), it causes errors on installation: `Error: can't get a valid version for repositories operator. Try changing the version constraint in Chart.yaml]`.

Right now it's impossible for us to use Redpanda because of this error (we want to switch from Kafka/Strimzi to Redpanda).

### What did you expect to happen?

A chart name with a prefix (`redpanda-operator`) allowing us to install our dependencies without errors.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>
Our `Chart.yaml`:

```yaml
apiVersion: v2
name: ...
type: application
version: 0.1.0
...
dependencies:
  - name: operator
    alias: minio-operator
    version: 5.0.10
    repository: https://operator.min.io/
    condition: minio-operator.enabled
  - name: tenant
    alias: minio
    version: 5.0.10
    repository: https://operator.min.io/
    condition: minio.enabled
  - name: operator
    alias: redpanda-operator
    version: 0.4.19
    repository: https://charts.redpanda.com
    condition: redpanda-operator.enabled
```

</details>

### Anything else we need to know?

I would say the other charts (`console`, `connectors`) are also likely to causes conflicts because of their names.

Note: It should also be noted that Helm developers are not willing to fix the underlying cause (see [issue](https://github.com/helm/helm/issues/7413)).

### Which are the affected charts?

Operator

### Chart Version(s)

Trying to install Redpanda Operator chart `v0.4.19`.

### Cloud provider

On-premise K8s cluster.
