### ISSUE TITLE
Add IP range to external section in values.yaml

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#106]
```
external:
  enabled: true
  # TODO include IP range for load balancer that support it: 
  type: LoadBalancer
  domain: redpanda.local
  ipRange:
  - 172.16.94.0
  - 172.16.94.254
  annotations:
    # cloud.google.com/load-balancer-type: "Internal"
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
