### ISSUE TITLE
Combine resource/cpu/memory sections

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#108]
Right now there are multiple locations where memory can be set depending on if it is for the pod, Redpanda, or Seastar. Move all these properties to a single section.

```
statefulset:
  resources:
    limits:
      cpu: "1"
      memory: 2.5Gi
  redpanda:
    memory: 2G
    reservedMemory: 400k
```
