### ISSUE TITLE
Admin listener target port mapping for the external LoadBalancer service.

### ISSUE THREAD

**Issue by ajurcenk** [redpanda-data/helm-charts#1113]
### What happened?

Admin listener external target port mapping for LoadBalancer service issue.
The admin listener configuration from Redpanda operator yaml
```yaml
    listeners:
      admin:
        external:
          default:
            port: 9645
            advertisedPorts:
            - 32006
            tls:
              cert: external
              enabled: true
```
The created LoadBalancer service yaml:
```yaml
  ports:
  - name: admin-default
    nodePort: 31097
    port: 32006
    protocol: TCP
    targetPort: 9644
```
The port `9644` is the internal Admin listener pod used in the LoadBalancer.
The port `9645` should be used for the target pod mapping.

### What did you expect to happen?

The port 9645 should be used for the target pod mapping.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Enable LoadBalancer, set the custom listener Admin port:
```yaml
    listeners:
      admin:
        external:
          default:
            port: 9645
            advertisedPorts:
            - 32006
            tls:
              cert: external
              enabled: true
```

### Anything else we need to know?

From the Helm LB template, the target port mapping logic `$values.listeners.admin.port`, we can get the target port from the `admin.port`, but if we have the custom external listener, we have to get from the listener port, like: `$listener.port`
From the `service.loadbalancer.yaml`:
```yaml
 ports:
    {{- range $name, $listener := $values.listeners.admin.external }}
      {{- $enabled := dig "enabled" $values.external.enabled $listener }}
      {{- if $enabled }}
    - name: admin-{{ $name }}
      protocol: TCP
      targetPort: {{ $values.listeners.admin.port }}
      port: {{ dig "nodePort" (first (dig "advertisedPorts" (list $values.listeners.admin.port) $listener)) $listener }}
      {{- end }}
    {{- end }}
```

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
NAME               	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION   
redpanda           	panda    	1       	2024-03-24 01:28:06.346536595 +0000 UTC	deployed	redpanda-5.7.35	v23.3.9       
redpanda-controller	panda    	1       	2024-03-22 11:59:13.831420496 -0400 EDT	deployed	operator-0.4.19	v2.1.14-23.3.4

```

</details>

### Cloud provider

<details>
kind, AKS
</details>
