### ISSUE TITLE
Can't upgrade redpanda from 5.7.35 to 5.7.36

### ISSUE THREAD

**Issue by tzahigro1** [redpanda-data/helm-charts#1128]
### What happened?

Trying to upgrade redpanda helm release from version 5.7.35 to 5.7.36 using openlens UI result in the following error:

`Error: Command failed: /Applications/OpenLens.app/Contents/Resources/x64/helm upgrade redpanda redpanda/redpanda --version 5.7.36 --values /private/var/folders/k6/870h7qy540x0fg8qflg389t80000gp/T/915d166c02eca01cd3560ed822484de5/values.yaml --namespace redpanda --kubeconfig /var/folders/k6/870h7qy540x0fg8qflg389t80000gp/T/kubeconfig-28802e1632c24b06e6d5ce5491b3c5fc
Error: UPGRADE FAILED: template: redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml:29:11: executing "redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml" at <include "full.labels" .>: error calling include: template: redpanda/templates/_helpers.tpl:43:11: executing "full.labels" at <include "redpanda.FullLabels" (dict "a" (list .))>: error calling include: template: redpanda/templates/_helpers.go.tpl:46:8: executing "redpanda.FullLabels" at <ne $values.commonLabels nil>: error calling ne: uncomparable type map[string]interface {}: map[]`

### What did you expect to happen?

Redpanda should be upgraded to version 5.7.36

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>
upgrade redpanda with the following values:
```
affinity: {}
auditLogging:
  clientMaxBufferSize: 16777216
  enabled: false
  enabledEventTypes: null
  excludedPrincipals: null
  excludedTopics: null
  listener: internal
  partitions: 12
  queueDrainIntervalMs: 500
  queueMaxBufferSizePerShard: 1048576
  replicationFactor: null
auth:
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    secretRef: redpanda-superusers
    users: []
clusterDomain: cluster.local
commonLabels: {}
config:
  cluster:
    default_topic_replications: 3
  node:
    crash_loop_limit: 5
  pandaproxy_client: {}
  rpk: {}
  schema_registry_client: {}
  tunable:
    compacted_log_segment_size: 67108864
    group_topic_partitions: 16
    kafka_batch_max_bytes: 1048576
    kafka_connection_rate_limit: 1000
    log_segment_size: 134217728
    log_segment_size_max: 268435456
    log_segment_size_min: 16777216
    max_compacted_log_segment_size: 536870912
    topic_partitions_per_shard: 1000
connectors:
  deployment:
    create: false
    podAntiAffinity:
      custom:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: redpanda-statefulset
              app.kubernetes.io/instance: redpanda
              app.kubernetes.io/name: redpanda
          topologyKey: kubernetes.io/hostname
    strategy:
      type: Recreate
  enabled: false
  monitoring: {}
  test:
    create: false
console:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: redpanda-statefulset
            app.kubernetes.io/instance: redpanda
            app.kubernetes.io/name: redpanda
        topologyKey: kubernetes.io/hostname
  annotations: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  commonLabels: {}
  config: {}
  configmap:
    create: false
  console:
    config: {}
  deployment:
    create: false
  enabled: true
  enterprise:
    licenseSecretRef:
      key: ""
      name: ""
  extraContainers: []
  extraEnv: []
  extraEnvFrom: []
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ""
  global: {}
  image:
    pullPolicy: IfNotPresent
    registry: docker.redpanda.com
    repository: redpandadata/console
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-realm: '"Authentication required"'
      nginx.ingress.kubernetes.io/auth-secret: redpanda-console
      nginx.ingress.kubernetes.io/auth-type: basic
    className: nginx
    enabled: true
    hosts:
    - host: console.mydomain.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - console.mydomain.com
      secretName: letsencrypt-prod-new-tls
  initContainers:
    extraInitContainers: ""
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    fsGroup: 99
    runAsUser: 99
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources: {}
  secret:
    create: false
    enterprise: {}
    kafka: {}
    login:
      github: {}
      google: {}
      jwtSecret: ""
      oidc: {}
      okta: {}
    redpanda:
      adminApi: {}
  secretMounts: []
  securityContext:
    runAsNonRoot: true
  service:
    annotations: {}
    port: 8080
    targetPort: null
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  strategy: {}
  tests:
    enabled: true
  tolerations: []
  topologySpreadConstraints: {}
enterprise:
  license: ""
  licenseSecretRef: {}
external:
  domain: redpanda.mydomain.com
  enabled: true
  service:
    enabled: true
  type: LoadBalancer
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: docker.redpanda.com/redpandadata/redpanda
  tag: ""
imagePullSecrets: []
license_key: ""
license_secret_ref: {}
listeners:
  admin:
    external:
      default:
        advertisedPorts:
        - 31644
        port: 9645
        tls:
          cert: external
    port: 9644
    tls:
      cert: default
      requireClientAuth: false
  http:
    authenticationMethod: null
    enabled: true
    external:
      default:
        advertisedPorts:
        - 30082
        authenticationMethod: null
        port: 8083
        tls:
          cert: external
          requireClientAuth: false
    kafkaEndpoint: default
    port: 8082
    tls:
      cert: default
      requireClientAuth: false
  kafka:
    authenticationMethod: null
    external:
      default:
        advertisedPorts:
        - 31092
        authenticationMethod: null
        port: 9094
        tls:
          cert: external
    port: 9093
    tls:
      cert: default
      requireClientAuth: false
  rpc:
    port: 33145
    tls:
      cert: default
      enabled: false
      requireClientAuth: false
  schemaRegistry:
    authenticationMethod: null
    enabled: true
    external:
      default:
        advertisedPorts:
        - 30081
        authenticationMethod: null
        port: 8084
        tls:
          cert: external
          requireClientAuth: false
    kafkaEndpoint: default
    port: 8081
    tls:
      cert: default
      requireClientAuth: false
logging:
  logLevel: info
  usageStats:
    enabled: true
monitoring:
  enabled: false
  labels: {}
  scrapeInterval: 30s
  tlsConfig: {}
nameOverride: ""
nodeSelector: {}
post_install_job:
  affinity: {}
  enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
post_upgrade_job:
  affinity: {}
  enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
rackAwareness:
  enabled: false
  nodeAnnotation: topology.kubernetes.io/zone
rbac:
  annotations: {}
  enabled: false
resources:
  cpu:
    cores: "1"
  memory:
    container:
      max: 10Gi
      min: 10Gi
    enable_memory_locking: true
serviceAccount:
  annotations: {}
  create: false
  name: ""
statefulset:
  additionalRedpandaCmdFlags: []
  annotations: {}
  budget:
    maxUnavailable: 1
  extraVolumeMounts: ""
  extraVolumes: ""
  initContainerImage:
    repository: busybox
    tag: latest
  initContainers:
    configurator:
      extraVolumeMounts: ""
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
    extraInitContainers: ""
    fsValidator:
      enabled: false
      expectedFS: xfs
      extraVolumeMounts: ""
      resources: {}
    setDataDirOwnership:
      enabled: false
      extraVolumeMounts: ""
      resources: {}
    setTieredStorageCacheDirOwnership:
      extraVolumeMounts: ""
      resources: {}
    tuning:
      extraVolumeMounts: ""
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
  nodeSelector: {}
  podAffinity: {}
  podAntiAffinity:
    custom: {}
    topologyKey: kubernetes.io/hostname
    type: hard
    weight: 100
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
  replicas: 2
  securityContext:
    allowPrivilegeEscalation: false
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
    runAsNonRoot: true
    runAsUser: 101
  sideCars:
    configWatcher:
      enabled: true
      extraVolumeMounts: ""
      resources: {}
      securityContext: {}
    controllers:
      createRBAC: true
      enabled: false
      healthProbeAddress: :8085
      image:
        repository: docker.redpanda.com/redpandadata/redpanda-operator
        tag: v2.1.10-23.2.18
      metricsAddress: :9082
      resources: {}
      run:
      - all
      securityContext: {}
  startupProbe:
    failureThreshold: 120
    initialDelaySeconds: 1
    periodSeconds: 10
  terminationGracePeriodSeconds: 90
  tolerations: []
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
storage:
  hostPath: /redpanda-data
  persistentVolume:
    annotations: {}
    enabled: true
    labels: {}
    nameOverwrite: ""
    size: 20Gi
    storageClass: ""
  tiered:
    config:
      cloud_storage_access_key: ""
      cloud_storage_api_endpoint: ""
      cloud_storage_azure_container: null
      cloud_storage_azure_shared_key: null
      cloud_storage_azure_storage_account: null
      cloud_storage_bucket: ""
      cloud_storage_cache_size: 5368709120
      cloud_storage_credentials_source: config_file
      cloud_storage_enable_remote_read: true
      cloud_storage_enable_remote_write: true
      cloud_storage_enabled: false
      cloud_storage_region: ""
      cloud_storage_secret_key: ""
    credentialsSecretRef:
      accessKey:
        configurationKey: cloud_storage_access_key
      secretKey:
        configurationKey: cloud_storage_secret_key
    hostPath: ""
    mountType: emptyDir
    persistentVolume:
      annotations: {}
      labels: {}
      storageClass: ""
tests:
  enabled: true
tls:
  certs:
    default:
      caEnabled: true
    external:
      caEnabled: false
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-prod
  enabled: true
tolerations: []
tuning:
  tune_aio_events: false
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
redpanda        redpanda        3               2024-04-01 17:25:18.491111 +0300 IDT    deployed        redpanda-5.7.35 v23.3.9  
```

</details>

### Cloud provider

<details>
Azure
</details>
