### ISSUE TITLE
Console Ingress should not default to a host of `chart-example.local`

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1130]
### What happened?

When not supplying a `hosts` array, the chart rendered with a host of `chart-example.local`

### What did you expect to happen?

No `host` to be defined, which is optional per https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Using the Operator, my Redpanda CR included the following section:

<details>

```
      ingress:
        enabled: true
        tls:
          - secretName: redpanda-external-cert
            hosts:
              - "console.redpanda-labs.com"
```

</details>

### Which are the affected charts?

Console

### Chart Version(s)

console-0.7.24

### Cloud provider

n/a
