### ISSUE TITLE
🫐 🐛 Operator doesn't seem to be taking `resources.memory.redpanda.*` values 

### ISSUE THREAD

**Issue by c4milo** [redpanda-data/helm-charts#1143]
### What happened?

```console
Events:
  Type     Reason            Age                   From                   Message
  ----     ------            ----                  ----                   -------
  Warning  InstallFailed     2m20s (x13 over 14m)  HelmReleaseReconciler  Helm install failed for release redpanda/redpanda-broker with chart redpanda@5.7.37: execution error at (redpanda/templates/configmap.yaml:27:9): unable to get memory value redpanda-memory
  
```

### What did you expect to happen?

I wanted to explicitly configure `--memory` and `--reserve-memory`

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```yaml
resources:
      memory:
        enable_memory_locking: true
        redpanda:
          memory: 2134
          reserveMemory: 0
```

</details>

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```console
❯ helm -n redpanda list
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
redpanda         	redpanda 	4       	2024-04-03 18:33:01.170109 -0400 EDT   	deployed	redpanda-0.1.1 	0.1.0
redpanda-broker  	redpanda 	1       	2024-04-03 22:28:53.750492162 +0000 UTC	deployed	redpanda-5.7.37	v23.3.10
redpanda-operator	redpanda 	1       	2024-04-01 18:14:29.732128 -0400 EDT   	deployed	operator-0.4.20	v2.1.15-23.3.7
```

</details>

### Cloud provider

<details>

</details>

**Comment by chrisseto** [comment]
@c4milo I think this is a duplicate of https://github.com/redpanda-data/helm-charts/issues/1134. Can you double check before I close this?

**Comment by c4milo** [comment]
I’m not sure, they don’t look similar since I can’t even set the
reserve-memory flags right now. So, I haven’t had a chance to see
duplicated CLI flags.

*Camilo Aguilar*

Software Engineer

redpanda.com | The streaming data platform for developers

Follow us on Twitter <https://twitter.com/redpandadata> | Join our community
<https://join.slack.com/t/redpandacommunity/shared_invite/zt-ng2ze1uv-l5VMWSGQHB9gp47~kNnYGA/>

**Comment by chrisseto** [comment]
Right, the linked issue and the fixing commit (https://github.com/redpanda-data/helm-charts/commit/ba7b6e3340fb279f562a9c4136ad813a135223bb) allow you to explicitly specify a value of `reserve-memory` in the `.statefulset.additionalRedpandaCmdFlags` field to bypass any of the calculations done by the chart/operator.

**Comment by c4milo** [comment]
then, yes, it should take care of this one too 👍🏻

**Comment by c4milo** [comment]
ah, @chrisseto, so you are saying I can't use these anymore? 

```
      memory:
        enable_memory_locking: true
        redpanda:
          memory: 2134
          reserveMemory: 0
```

**Comment by chrisseto** [comment]
You can and that will continue to set the resource requests/limits on the pod and the flags. However, if you want to explicitly control the values of the flags you can do this:

```
      memory:
        enable_memory_locking: true
        redpanda:
          memory: 2134
          reserveMemory: 0

statefulset:
  additionalRedpandaCmdFlags:
    - --memory=1234
    - --reserve-memory=0
```
