### ISSUE TITLE
Helm chart not properly restarting pods after initial tiered storage settings are applied

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1173]
### What happened?

With a new deployment, my tiered storage settings are not activated. Looking at the cluster, it's in a state saying it requires restart:

```
redpanda@redpanda-0:/$ rpk -Xuser=admin -Xpass=xxx config status
NODE  CONFIG-VERSION  NEEDS-RESTART  INVALID  UNKNOWN
0     4               true           []       []
1     4               true           []       []
2     4               true           []       []
```

### What did you expect to happen?

Tiered storage settings should be activated with my settings.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Deploy Redpanda via Helm using some of the following storage settings:

```yaml
storage:
  persistentVolume:
    enabled: true
    storageClass: csi-driver-lvm-striped-xfs
  tiered:
    config:
      cloud_storage_enabled: true
      cloud_storage_api_endpoint: storage.googleapis.com
      cloud_storage_credentials_source: gcp_instance_metadata
      cloud_storage_enable_remote_write: true
      cloud_storage_enable_remote_read: true
      cloud_storage_region: my-region
      cloud_storage_bucket: my-bucket
```

### Anything else we need to know?

A workaround is to force a restart via:

```
kubectl rollout restart statefulset/redpanda 
```

### Which are the affected charts?

Redpanda

### Chart Version(s)

5.7.37

### Cloud provider

GCP / GKE

JIRA Link: [K8S-146](https://redpandadata.atlassian.net/browse/K8S-146)

[K8S-146]: https://redpandadata.atlassian.net/browse/K8S-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
