### ISSUE TITLE
Incorrect capitalization of `securityContext`

### ISSUE THREAD

**Issue by Tolsto** [redpanda-data/helm-charts#1240]
### What happened?

The `RedPanda` CRD defines `clusterSpec.statefulset.sideCars.configWatcher.SecurityContext` (with a capital `S`) and will pass it on as `SecurityContext` to the values section of the `HelmRelease`. However, the chart expects `securityContext`. As a result, the configured config watcher security context will be missing.

### What did you expect to happen?

Configuring the config watcher security context via the CRD should add it to the statefulset.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    statefulset:
      sideCars:
        configWatcher:
          SecurityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
```

### Chart Version(s)

chart repo commit f09c338cb40aceda1578ad724ef5b155765f41d5

### Cloud provider

AWS EKS
