### ISSUE TITLE
Tiered Storage cluster property `cloud_storage_bucket` is not actually required.

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1260]
### What happened?

A user configuring Tiered Storage for use with Azure Blob Storage configured the cluster properties per our documentation. This results in the Helm chart producing an error during validation like:

```
one or more objects failed to apply, reason: [Redpanda.cluster.redpanda.com](http://redpanda.cluster.redpanda.com/) "redpanda-cluster-xyzzy" is invalid: spec.clusterSpec.storage.tiered.config.cloud_storage_bucket: Required value
```

It seems like the validation logic [here](https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/values.go#L684) is incorrectly flagging this property as required.

### What did you expect to happen?

No validation error.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Use a Helm values including something like the following Azure Blob settings:

```
storage:
  persistentVolume:
  tiered:
    config:
      cloud_storage_azure_adls_endpoint: xyzzy.blob.core.windows.net
      cloud_storage_azure_adls_port: "443"
      cloud_storage_azure_shared_key: <some path for a key>
      cloud_storage_azure_storage_account: xyzzyaccount
      cloud_storage_azure_storage_container: xyzzy-cluster1
      cloud_storage_enabled: "true"
```

### Anything else we need to know?

Internal discussion: https://redpandadata.slack.com/archives/C02BDN76HUK/p1714404668077659

### Which are the affected charts?

Redpanda

### Chart Version(s)

`5.8.0`

### Cloud provider

Azure

**Comment by voutilad** [comment]
A workaround for now is to set a junk value for `cloud_storage_bucket` to make Helm happy and the TS framework will ignore it if the required Azure Blob properties are set.

**Comment by RafalKorepta** [comment]
@voutilad 

From your example
```yaml
storage:
  persistentVolume:
  tiered:
    config:
      cloud_storage_azure_adls_endpoint: xyzzy.blob.core.windows.net
      cloud_storage_azure_adls_port: "443"
      cloud_storage_azure_shared_key: <some path for a key>
      cloud_storage_azure_storage_account: xyzzyaccount
      cloud_storage_azure_storage_container: xyzzy-cluster1
      cloud_storage_enabled: "true"
```

The `cloud_storage_azure_storage_container` is not available.

https://docs.redpanda.com/current/reference/cluster-properties/#cloud_storage_azure_container There is `cloud_storage_azure_container`.

Thanks to @JakeSCahill https://github.com/redpanda-data/redpanda-operator/pull/127 should fix this, but we need to release this fix (it's not done with PR merge).
