### ISSUE TITLE
HELM v0.4.19 chart Cluster Role definitions cause conflicting resources

### ISSUE THREAD

**Issue by jeroenrinzema** [redpanda-data/helm-charts#1266]
### What happened?

Changes introduced in `v0.4.19` are causing `ClusterRole` resources to conflict when Redpanda cluster are created using the same name. In addition does this change require the runner deploying the HELM charts to be granted `ClusterRole` rights in order to deploy a Redpanda cluster in a isolated namespace. This is currently affecting our deployment pipelines and are forced to downgrade to `v0.4.18` due to the `ClusterRoles` that are attempted to be created without the ability to disable these resources.

### What did you expect to happen?

The ability to disable the creation of all Cluster wide resources while deploying the Redpanda operator within a isolated namespace as previously possible in `v0.4.18`. https://github.com/redpanda-data/helm-charts/commit/b20d91efbb31d4c9e83be0d76df38fc6842435de

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```
redpanda:
  enabled: false
  scope: Namespace
  fullnameOverride: redpanda-operator
  image:
    tag: v2.1.16-23.3.11
  config:
    leaderElection:
      leaderElect: false
```

### Which are the affected charts?

Operator

### Chart Version(s)

`v0.4.21`

### Cloud provider

Azure AKS
