### ISSUE TITLE
Improve liveness probe to utilize to use builtin http probe instead of curl

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/helm-charts#1278]
### What would you like to be added?

Update the liveness probe to utilize the builtin-in http check rather than a curl. 

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

```
          # the livenessProbe just checks to see that the admin api is listening and returning 200s.
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl --silent --fail -k  "http://${SERVICE_NAME}.redpanda-cluster.prod.svc.cluster.local.:9644/v1/status/ready"
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 10
```

See additional details in slack thread: https://redpandadata.slack.com/archives/C01H6JRQX1S/p1715624674945489

### Why is this needed?

This would avoid a slow `exec` out to `curl` and reduce the surface area of failure should a DNS resolution not work out per the way we currently do the liveness probe (k8s cluster DNS failure could cause cascading failure of the Redpanda cluster even though RP may be alive and healthy).
