### ISSUE TITLE
Kminion's Helm chart installs buggy version of Kminion: 2.2.5

### ISSUE THREAD

**Issue by c4milo** [redpanda-data/helm-charts#1286]
### What happened?

```
│ {"level":"fatal","ts":1715980546.5169997,"caller":"app/main.go:44","msg":"failed to parse config","error":"1 err │
│ or(s) decoding:\n\n* 'minion.topics' has invalid keys: enabled","stacktrace":"main.main\n\t/app/main.go:44\nrunt │
│ ime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

### What did you expect to happen?

No errors in the logs

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Install Kminion Helm chart and configure it with the following: 

```yaml
kminion:
  # Reference: https://github.com/cloudhut/kminion/blob/master/docs/reference-config.yaml
  config:
    minion:
      topics:
        enabled: false
```
</details>

### Anything else we need to know?

The bug was patched in 2.2.8: https://github.com/redpanda-data/kminion/commit/1f1fe713fd59800d43a96d27cdabde670d5f894a

### Which are the affected charts?

Kminion

### Chart Version(s)

0.12.7

### Cloud provider

Azure

JIRA Link: [K8S-225](https://redpandadata.atlassian.net/browse/K8S-225)

[K8S-225]: https://redpandadata.atlassian.net/browse/K8S-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
