### ISSUE TITLE
how to integrate redpanda-console with kafka strimzi with tls enabled

### ISSUE THREAD

**Issue by andreyolv** [redpanda-data/helm-charts#1306]
### What happened?

I don't know how to integrate redpanda-console with kafka-strimzi with tls enabled. It would be interesting to have a clear example.

### What did you expect to happen?

I wish it worked.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Using kafka strimzi with tls create user 'user-admin' (this will create a secret with the same name containing the certificates for the user)

Fill configurations helm chart redpanda-console values:
```
    console:
      config:
        logger:
          level: debug
        kafka:
          brokers:
            - kafka-bootstrap.kafka-strimzi.svc.cluster.local:9093
          tls:
            enabled: true
            caFilepath: "/etc/kafka/certs/ca.crt"
            certFilepath: "/etc/kafka/certs/user.crt"
            keyFilepath: "/etc/kafka/certs/user.key"
    extraVolumes:
    - name: kafka-certs
      secret:
        secretName: user-admin
    extraVolumeMounts:
    - name: kafka-certs
      mountPath: /etc/kafka/certs
      readOnly: true
```

logs:
```
{"level":"warn","ts":"2024-05-23T01:38:16.518Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"kafka-bootstrap.kafka-strimzi.svc.cluster.local:9093","broker":"seed_0","err":"tls: failed to verify certificate: x509: certificate signed by unknown authority"}
{"level":"warn","ts":"2024-05-23T01:38:16.518Z","msg":"Failed to test Kafka connection, going to retry in 8s","remaining_retries":2}
{"level":"info","ts":"2024-05-23T01:38:24.523Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"debug","ts":"2024-05-23T01:38:24.523Z","logger":"kafka_client","msg":"opening connection to broker","addr":"kafka-bootstrap.kafka-strimzi.svc.cluster.local:9093","broker":"seed_0"}
{"level":"debug","ts":"2024-05-23T01:38:24.533Z","logger":"kafka_client_hooks","msg":"kafka connection failed","broker_host":"kafka-bootstrap.kafka-strimzi.svc.cluster.local","error":"tls: failed to verify certificate: x509: certificate signed by unknown authority"}
{"level":"warn","ts":"2024-05-23T01:38:24.533Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"kafka-bootstrap.kafka-strimzi.svc.cluster.local:9093","broker":"seed_0","err":"tls: failed to verify certificate: x509: certificate signed by unknown authority"}
{"level":"warn","ts":"2024-05-23T01:38:24.533Z","msg":"Failed to test Kafka connection, going to retry in 16s","remaining_retries":1}
```

### Which are the affected charts?

Console

### Chart Version(s)

0.7.26

### Cloud provider

AKS (Azure Kubernetes Service)
