### ISSUE TITLE
redpanda: add unit tests for `soft` anti-affinities

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1328]
As discovered in https://github.com/redpanda-data/helm-charts/pull/1327, it seems that `soft` anti-affinities do not have any test coverage and they generate some questionable YAML:

```bash
helm template rp ./charts/redpanda/ --set 'statefulset.podAntiAffinity.type=soft'
```

(Note that `matchLabels`) doesn't have an appropriate indentation.
```yaml
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                app.kubernetes.io/component: redpanda-statefulset
                app.kubernetes.io/instance: rp
                app.kubernetes.io/name: redpanda
```

For whatever reason, some YAML parsers appear to be okay with this syntax while others are less tolerant. If possible, we should add a more strict YAML validator/parser to our test cases.

JIRA Link: [K8S-241](https://redpandadata.atlassian.net/browse/K8S-241)
