### ISSUE TITLE
🫐 When passing Redpanda TLS certs as a secret and enabling mTLS, rpk commands run by the Helm chart are unable to authenticate

### ISSUE THREAD

**Issue by c4milo** [redpanda-data/helm-charts#1348]
### What happened?

This is since the TLS certs Certificate Authority (CA) or cluster issuer (in cert-manager parlance) isn't necessarily managed by the Helm Chart, so the current hardcoded TLS cert paths for RPK are not going to exist or be signed by the same CA as the brokers certificates. 

### What did you expect to happen?

rpk client certs to be passed through a secret ref field. 

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

1. Pass brokers TLS certs as a secret ref
2. Enable mTLS in Redpanda
3. RPK will be unable to authenticate against Redpanda

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

JIRA Link: [K8S-257](https://redpandadata.atlassian.net/browse/K8S-257)

[K8S-257]: https://redpandadata.atlassian.net/browse/K8S-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by RafalKorepta** [comment]
@c4milo With https://github.com/redpanda-data/helm-charts/pull/1402 you should be able to use mTLS by providing 2 information in TLS section.

Please see the following example:
```yaml
listeners:
  admin:
    tls:
      cert: provided
      requireClientAuth: true
  http:
    tls:
      cert: provided
      requireClientAuth: true
  kafka:
    tls:
      cert: provided
      requireClientAuth: true
  rpc:
    tls:
      cert: provided
      requireClientAuth: true
  schemaRegistry:
    tls:
      cert: provided
      requireClientAuth: true
tls:
  certs:
    default:
      enabled: false
    provided:
      caEnabled: true
      clientSecretRef:
        name: client-tls-secret
      enabled: true
      secretRef:
        name: server-tls-secret
  enabled: true
```

1. I disabled the default certificate (you can use the `default` but maybe it would be better to change that name that suites you)
2. I provided clientSecretRef for rpk to use.
3. I provided secretRef for Redpanda to use across all listeners. 

### Reference

https://github.com/redpanda-data/helm-charts/pull/1402
https://github.com/redpanda-data/redpanda-operator/pull/170
