### ISSUE TITLE
Configuring security context privilege escalation value

### ISSUE THREAD

**Issue by nick-jones** [redpanda-data/helm-charts#1413]
### What happened?

For the redpanda chart, I've been looking to get `securityContext` configured with `allowPrivilegeEscalation` set to `false`. Unfortunately it kept being rendered as `allowPrivilegeEscalation: null`. I've just noticed that the templating expects `allowPriviledgeEscalation` to be configured. This is a bit subtle, but take note that "allowPrivile**d**geEscalation" != "allowPrivilegeEscalation".

The kubernetes security context key is `allowPrivilegeEscalation`, so I think generally people would expect this to be aligned (and beyond all of that, "priviledge" is not any valid alternative spelling).

### What did you expect to happen?

I should be able to use the following values, and get a statefulset with the container security context including `allowPrivilegeEscalation: false`

```yaml
    statefulset:
      replicas: 3
      securityContext:
        allowPrivilegeEscalation: false
```

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```yaml
    statefulset:
      replicas: 3
      securityContext:
        allowPrivilegeEscalation: false
```

### Anything else we need to know?

- https://github.com/search?q=repo%3Aredpanda-data%2Fhelm-charts%20allowPriviledgeEscalation&type=code
- https://github.com/redpanda-data/helm-charts/blob/7648b58b9e02e3feebc4b7c797724c3728fd738b/charts/redpanda/templates/_helpers.go.tpl#L265

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>
5.8.12
</details>

### Cloud provider

<details>
N/A
</details>

JIRA Link: [K8S-286](https://redpandadata.atlassian.net/browse/K8S-286)
