### ISSUE TITLE
Add support for Certificate Revocation Lists (CRL) in Helm chart

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#1429]
### What would you like to be added?

[In 24.2, Redpanda will support Certificate Revocation Lists (CRLs)](https://github.com/redpanda-data/documentation-private/issues/2580) for TLS-encrypted connections. To support CRLs in the Helm chart, we require some changes.

**Changes Required**

Update `values.yaml` to add new fields under the `tls` section for each listener to specify the CRL paths. For example:

```yaml
tls:
  enabled: true
  certs:
    default:
      caEnabled: true
    external:
      caEnabled: true

  # Global CRL field
  crlSecret: "global-crl-secret"
  crlFile: "/etc/tls/crl/global-crl.pem"

listeners:
  admin:
    port: 9644
    tls:
      cert: default
      requireClientAuth: false
      crlSecret: "admin-crl-secret"
      crlFile: "/etc/tls/crl/admin-crl.pem"
    external:
      default:
        port: 9645
        tls:
          cert: external
          crlSecret: "admin-external-crl-secret"
          crlFile: "/etc/tls/crl/admin-external-crl.pem"

  kafka:
    port: 9093
    authenticationMethod: "sasl"
    tls:
      cert: default
      requireClientAuth: false
      crlSecret: "kafka-crl-secret"
      crlFile: "/etc/tls/crl/kafka-crl.pem"
    external:
      default:
        port: 9094
        tls:
          cert: external
          crlSecret: "kafka-external-crl-secret"
          crlFile: "/etc/tls/crl/kafka-external-crl.pem"

  # Other listeners...

```

### Why is this needed?

To support the new CRL `crl_file` field in Redpanda >=24.2
