### ISSUE TITLE
`external.addresses` isn't used by external-dns

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#1470]
### What happened?

I'm setting the domain and addresses in the external section of the helm chart:
```
    external:
      domain: pnda.sh
      addresses:
        - redpanda-0-dev-ap-southeast-2
        - redpanda-1-dev-ap-southeast-2
        - redpanda-2-dev-ap-southeast-2
```

I'm also using external-dns annotations so A records get created for each broker. These records get created, but instead the records are for:
1. redpanda-0.pnda.sh
2. redpanda-1.pnda.sh
3. redpanda-2.pnda.sh

### What did you expect to happen?

These should be using the details provided in the external section above.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>
