### ISSUE TITLE
Annotations for post_install_job and post_upgrade_job are not passed to the job template

### ISSUE THREAD

**Issue by zs-ko** [redpanda-data/helm-charts#1474]
### What would you like to be added?

Add annotations from the job to the jobtemplate so the pods created inherit the annotations or allow for customizing the job template annotations.

When running with a service mesh like istio the injected sidecar needs to start up before the job tries to connec or else the job fails since it has no retry. adding an annotation can allow istio to hold the job until its sidecar is started up

### Why is this needed?

Allow for service meshes to read the annotation and hold jobs until its ready to serve traffic.  Istio can hold a job until the proxy is runnig so that the job can communicate with the nodes.

```yaml
post_install_job:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```

JIRA Link: [K8S-312](https://redpandadata.atlassian.net/browse/K8S-312)

**Comment by chrisseto** [comment]
I think this will be fixed once https://github.com/redpanda-data/helm-charts/pull/1477 lands.

To apply annotations to the Job's Pod you'd specify:

```yaml
post_install_job:
  podTemplate:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```
