### ISSUE TITLE
Expose the StatefulSet for use external to Kubernetes

### ISSUE THREAD

**Issue by BenPope** [redpanda-data/helm-charts#15]
A client needs to access each specific broker, so a LoadBalancer is needed for each broker.

The broker needs to advertise the address of the LoadBalancer, which is a little more tricky. I think it would be worth investigating https://github.com/kubernetes-sigs/external-dns - this should allow a predictable DNS entry for each LoadBalancer  associated with each Redpanda broker, and generate the `advertised_kafka_api` with helm. Some docs here: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md

Something like:

service.loadbalancer.yaml
```yaml
{{- $lb := .Values.loadBalancer }}
{{- if $lb.enabled }}
{{- range untilStep 0 (.Values.statefulset.replicas|int) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: redpanda-{{ . }}
annotations:
  external-dns.alpha.kubernetes.io/hostname: redpanda-{{ . }}.{{.Values.loadBalancer.parentZone}}
spec:
  externalTrafficPolicy: Local
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-{{ . }}
  type: LoadBalancer
---
{{- end }}
{{- end }}
```

statefulset.yaml
```yaml
rpk --config $CONFIG config set redpanda.advertised_kafka_api.address redpanda-$NODE_ID.{{.Values.loadBalancer.parentZone}}
```

Values.yaml
```yaml
loadBalancer:
  enabled: true
  parentZone: my-project.gcp.domain.com.
```

Currently Redpanda can currently only [listen on one address](https://github.com/vectorizedio/redpanda/issues/186), which means traffic inside the K8s cluster would have to go via the LoadBalancer.
