### ISSUE TITLE
Error when trying to mount an extra volume in statefulset

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#1539]
### What happened?

Using the following `values.yaml`:
```
statefulset:
  extraVolumes: |-
    - name: redpanda-io-config
      configMap:
        name: redpanda-io-config
  extraVolumeMounts: |-
    - name: redpanda-io-config
      mountPath: /etc/redpanda-io-config
  additionalRedpandaCmdFlags:
    - "--io-properties-file=/etc/redpanda-io-config/io-config.yaml"
```

And the following command:
```
helm upgrade --install redpanda redpanda --repo https://charts.redpanda.com -n redpanda --wait --timeout 2h --create-namespace -f values.yaml --dry-run --debug
```

Results in the following error:
[output.log](https://github.com/user-attachments/files/17100839/output.log)

### What did you expect to happen?

Should have not failed

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

See details above.

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

chart v5.9.4

</details>

### Cloud provider

<details>
none
</details>
