### ISSUE TITLE
Setup cluster with TLS from a K8s secret doesn't work

### ISSUE THREAD

**Issue by itamararjuan** [redpanda-data/helm-charts#1572]
### What happened?

My network is internal in my EKS cluster and so I cannot use cert-manager to create a Let's Encrypt certificate. So I have used certbot to create the certificates to my brokers with a DNS challenge which I completed manually.

I then went ahead and inserted the certificate files into a K8s secret just as the documentation asks to do.
I went ahead and fired up a cluster referrencing the secret in the external listeners section

### What did you expect to happen?

I expected the cluster to consume the secret content and be able to configure the TLS of the brokers correctly.
but instead, the cluster didn't come up and the logs from the pods said that there is no such file for the ca.crt file
even though I've made a certificate using Let's Encrypt, therefore a public CA not needing to specify a ca.crt file

I also tried to mitigate this by trying to create a generic secret and putting the supplied chain (CA.crt) of Let's encrypt which was provided with the certificate by certbot and tried referncing also that generic secret but again, the cluster won't come up.

Esentially I'm not able to setup a TLS enabled cluster in any other mode other than using a self signed certificate by cert-manager.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: 5.9.6
  clusterSpec:
    external:
      enabled: true
      domain: redpanda.example.com
      type: NodePort
    tls:
      enabled: true
      certs:
        external:
          secretRef:
            name: rp-data-tls

    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: secretpassword
    storage:
      persistentVolume:
        enabled: true
        storageClass: gp2 // just an example

```

### Chart Version(s)

5.9.6

### Cloud provider

<details>
AWS - EKS
</details>

**Comment by chrisseto** [comment]
Could you share the logs from redpanda when it's refusing to start up and the redacted contents of your secret, really just the keys would be fine?

**Comment by itamararjuan** [comment]
Just saw now that you replied - of course!

Let's start by the secret , so I'm creating a TLS type secret using the method supplied in the documentation
like so:

```
kubectl create secret tls rp-data-tls \
  --cert=certs/tls.crt \
  --key=certs/tls.key \
  --namespace redpanda-data
```

The files are the actual certificate which I've made with certbot - I copied those files and renamed them from the following available files that I got when using certbot.

I renamed the `cert.pem` to `tls.crt` and `privkey.pem` to `tls.key` and just referenced those files here

The logs of the nodes when they try to come up complain about not having the ca.crt availble (As it red panda is expecting it) even though this certificate was created with a public CA (let's encrypt using certbot cli for macOS)

I'll comment with the actual error in a small bit.

**Comment by itamararjuan** [comment]
My yaml for creating the cluster is the following:

```
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: 5.9.9
  clusterSpec:
    nodeSelector:
      purpose: "red-panda-cluster"
    external:
      enabled: true
      domain: redpanda-data.k8s.staging.mycompanydomain.com
      type: NodePort
    tls:
      enabled: true
      certs:
        external:
          secretRef:
            name: rp-data-tls

    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: secretpassword
    storage:
      persistentVolume:
        enabled: true
        storageClass: csi-driver-ebs-gp3

```
