### ISSUE TITLE
commonLabels are not inherited to the console pods

### ISSUE THREAD

**Issue by togge** [redpanda-data/helm-charts#1581]
### What happened?

Setting the commonLabels works for the statefulset pods, but not for the console pod

### What did you expect to happen?

As specified in the documentation:
```yaml
# -- Additional labels to add to all Kubernetes objects.
# For example, `my.k8s.service: redpanda`.
commonLabels: {}
```

I would think that the console pod would inherit these labels as well?

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```yaml
   commonLabels:
      ingress.home.arpa/lan: allow
      egress.home.arpa/apiserver: allow
      egress.home.arpa/kubedns: allow
    tls:
      enabled: false
    external:
      enabled: true
      type: NodePort
    storage:
      persistentVolume:
        size: 3Gi
        storageClass: "ceph-block"
```

### Chart Version(s)

5.9.9

### Cloud provider

<details>
Talos
</details>

JIRA Link: [K8S-405](https://redpandadata.atlassian.net/browse/K8S-405)

[K8S-405]: https://redpandadata.atlassian.net/browse/K8S-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by RafalKorepta** [comment]
@togge I see the confusion. That `commonLabels ` is not passed to subcharts. If you would like to use labels in Console subchart you should add the following values to your helm chart values.
```yaml
console:
  commonLabels:
    ingress.home.arpa/lan: allow
    egress.home.arpa/apiserver: allow
    egress.home.arpa/kubedns: allow
```

If you will find any problem with that please re-open this issue.
