### ISSUE TITLE
Helm: allow adding annotations to generated secrets

### ISSUE THREAD

**Issue by AsoTora** [redpanda-data/helm-charts#1629]
### What happened?

Installed helm chart for a production workload generates the TLS certificates with default labels and annotations:

`kubectl describe secret redpanda-default-cert -n redpanda`
```yaml
Name:         redpanda-default-cert
Namespace:    redpanda
Labels:       controller.cert-manager.io/fao=true
Annotations:  cert-manager.io/alt-names:
                redpanda-cluster.redpanda.redpanda.svc.cluster.local,redpanda-cluster.redpanda.redpanda.svc,redpanda-cluster.redpanda.redpanda,*.redpanda-...
              cert-manager.io/certificate-name: redpanda-default-cert
              cert-manager.io/common-name:
              cert-manager.io/ip-sans:
              cert-manager.io/issuer-group: cert-manager.io
              cert-manager.io/issuer-kind: Issuer
              cert-manager.io/issuer-name: redpanda-default-root-issuer
              cert-manager.io/uri-sans:
Type:  kubernetes.io/tls

Data
====
ca.crt:   *** bytes
tls.crt:  *** bytes
tls.key:  *** bytes
```

What I'm doing right now is propagating this TLS certificate to other namespaces via the https://github.com/emberstack/kubernetes-reflector, which requires annotating the secret, which isn't possible via the helm chart.

### What did you expect to happen?

Ability to set the self-generated secrets annotation via `values.yml`

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Values:

```yaml
    external: 
      enabled: true
      domain: *****
      type: NodePort
      annotations:
        external-dns.alpha.kubernetes.io/endpoints-type: NodeExternalIP
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-512
        secretRef: "redpanda-users"
        ...
    resources:
    ...

    console:
      enabled: true
      configmap:
        create: false
      secret:
        create: false
      deployment:
        create: false
      annotations:
        reloader.stakater.com/auto: "true"
      ingress:
        enabled: true
        ...

```

### Which are the affected charts?

Redpanda

### Chart Version(s)

- 5.8.15
- 5.9.17

### Cloud provider

kubernetes v1.29.9
