### ISSUE TITLE
redpanda console config regression

### ISSUE THREAD

**Issue by kperreau** [redpanda-data/helm-charts#1635]
### What happened?

My previous config for redpanda console is not working anymore.

### What did you expect to happen?

Works as before and as stated in the documentation.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

My previous config:
```console
console:
  secret:
    create: true
    kafka:
      protobufGitBasicAuthPassword: overwrite-by-external-secret
  config:
    kafka:
      protobuf:
        enabled: true
        mappings:
          - topicName: my-topic
            valueProtoType: package.Object
        git:
          enabled: true
          refreshInterval: 5m
          repository:
            url: https://github.com/my/repo.git
            branch: redpanda
          basicAuth:
            enabled: true
            username: token
```

New working config:
```console
console:
  secret:
    create: true
    kafka:
      protobufGitBasicAuthPassword: overwrite-by-external-secret
  console:  # <----------------- notice the extra console: here
    config:
      kafka:
        protobuf:
          enabled: true
          mappings:
            - topicName: my-topic
              valueProtoType: package.Object
          git:
            enabled: true
            refreshInterval: 5m
            repository:
              url: https://github.com/my/repo.git
              branch: redpanda
            basicAuth:
              enabled: true
              username: token
```

</details>

### Anything else we need to know?

As a reminder, the documentation provides this:
https://artifacthub.io/packages/helm/redpanda-data/redpanda?modal=values&path=console

```yaml
# -- Redpanda Console settings.
# For a reference of configuration settings,
# see the [Redpanda Console documentation](https://docs.redpanda.com/docs/reference/console/config/).
console:
  enabled: true
  configmap:
    create: false
  secret:
    create: false
  deployment:
    create: false
  config: {}
```

If I am mistaken, you can close this issue. In any case, I was ultimately able to get the configuration to work. However, since it worked differently before and no mention of this change is documented, I thought it would be good to raise an issue just in case.

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
redpanda        redpanda        16              2025-01-14 17:20:15.33898 +0100 CET     deployed        redpanda-5.9.18 v24.3.2    
```

</details>

### Cloud provider

<details>
Bare metal microk8s
</details>
