### ISSUE TITLE
Fluxcd error message when deploying redpanda/operator in k8s

### ISSUE THREAD

**Issue by Aangbaeck** [redpanda-data/helm-charts#1639]
### What happened?

I tried deploying the operator via ArgoCD in a AKS k8s cluster (V1.28.13) and no specific settings, everything is default.
I used the namespace "operators"
When deploying the i get the error:

```
{"level":"info","ts":"2025-02-07T07:58:57.048Z","msg":"running in v2","mode":"Namespaced-v2","helm controllers enabled":true,"namespace":"operators"}
{"level":"error","ts":"2025-02-07T07:58:57.087Z","logger":"setup","msg":"Unable to create flux controller","error":"failed setting index fields: failed to get restmapping: no matches for kind \"HelmRepository\" in group \"source.toolkit.fluxcd.io\""}
Error: failed setting index fields: failed to get restmapping: no matches for kind "HelmRepository" in group "source.toolkit.fluxcd.io"
Usage:
  redpanda-operator run [flags]
Flags:
      --additional-controllers strings                     which controllers to run, available: all, nodeWatcher, decommission
      --allow-console-any-ns                               Allow to create Console in any namespace. Allowing this copies Redpanda SchemaRegistry TLS Secret to namespace (alpha feature)
      --allow-downscaling                                  Allow to reduce the number of replicas in existing clusters (default true)
      --allow-pvc-deletion                                 Deprecated: Ignored if specified
      --auto-delete-pvcs                                   Use StatefulSet PersistentVolumeClaimRetentionPolicy to auto delete PVCs on scale down and Cluster resource delete.
      --cluster-domain string                              Set the Kubernetes local domain (Kubelet's --cluster-domain) (default "cluster.local")
      --configurator-base-image string                     Set the configurator base image (default "docker.redpanda.com/redpandadata/redpanda-operator")
      --configurator-image-pull-policy string              Set the configurator image pull policy (default "Always")
      --configurator-tag string                            Set the configurator tag (default "2.3.6-24.3.3-SNAPSHOT-8d4e9417")
      --debug                                              A deprecated and unused flag
      --decommission-wait-interval duration                Set the time to wait for a node decommission to happen in the cluster (default 8s)
      --enable-helm-controllers                            if a namespace is defined and operator mode is true, this enables the use of helm controllers to manage fluxcd helm resources. (default true)
      --events-addr string                                 A deprecated and unused flag
      --force-defluxed-mode                                specifies the default value for useFlux of Redpanda CRs if not specified. May be used in conjunction with enable-helm-controllers=false
      --health-probe-bind-address string                   The address the probe endpoint binds to. (default ":8081")
      --helm-repository-url https://charts.redpanda.com/   URL to overwrite official https://charts.redpanda.com/ Redpanda Helm chart repository (default "https://charts.redpanda.com/")
  -h, --help                                               help for run
      --insecure-kubeconfig-exec                           Allow use of the user.exec section in kubeconfigs provided for remote apply.
      --insecure-kubeconfig-tls                            Allow that kubeconfigs provided for remote apply can disable TLS verification.
      --kube-api-burst int                                 The maximum burst queries-per-second of requests sent to the Kubernetes API. (default 300)
      --kube-api-qps float32                               The maximum queries-per-second of requests sent to the Kubernetes API. (default 50)
      --leader-elect                                       Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
      --metrics-bind-address string                        The address the metric endpoint binds to. (default ":8080")
      --metrics-timeout duration                           Set the timeout for a checking metrics Admin API endpoint. If set to 0, then the 2 seconds default will be used (default 8s)
      --namespace string                                   If namespace is set to not empty value, it changes scope of Redpanda operator to work in single namespace
      --operator-mode                                      enables to run as an operator, setting this to false will disable cluster (deprecated), redpanda resources reconciliation. (default true)
      --pprof-bind-address string                          The address the metric endpoint binds to. Set to '' or 0 to disable (default ":8082")
      --restrict-redpanda-version string                   Restrict management of clusters to those with this version
      --superusers-prefix string                           Prefix to add in username of superusers managed by operator. This will only affect new clusters, enabling this will not add prefix to existing clusters (alpha feature)
      --unbind-pvcs-after duration                         if not zero, runs the PVCUnbinder controller which attempts to 'unbind' the PVCs' of Pods that are Pending for longer than the given duration
      --unbinder-label-selector label selector             if provided, a Kubernetes label selector that will filter Pods to be considered by the PVCUnbinder.
      --webhook-enabled                                    Enable webhook Manager
Global Flags:
      --log-encoding string   Log encoding format. Can be 'json' or 'console'. (default "json")
      --log-level string      Log verbosity level. Can be one of 'trace', 'debug', 'info', 'error'. (default "info")
failed setting index fields: failed to get restmapping: no matches for kind "HelmRepository" in group "source.toolkit.fluxcd.io"
```

### What did you expect to happen?

I have no specific settings in the deployment so I thought it should just work. Have I missed some dependencies or settings? I have deployed many other type of operators the exact same way and they work perfectly.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

I just deploy it with an Argo "ApplicationSet".
<details>

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redpanda-operator
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            app.kubernetes.io/managed-by: argocd
  syncPolicy: {}
  template:
    metadata:
      name: "redpanda-operator-{{name}}"
    spec:
      project: "default"
      sources:
      - repoURL: https://charts.redpanda.com
        chart: operator
        targetRevision: "0.4.39"
        helm:
          releaseName: redpanda-operator
          valueFiles:
          - $values/apps/redpanda-operator/{{ name }}/values.yaml
      destination:
        name: "{{name}}"
        namespace: operators
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
```

</details>

### Which are the affected charts?

Operator

### Chart Version(s)

<details>

```console
redpanda/operator       0.4.39          v2.3.6-24.3.3   Redpanda operator helm chart
```

</details>

### Cloud provider

<details>
Azure AKS 1.28.13
</details>

JIRA Link: [K8S-501](https://redpandadata.atlassian.net/browse/K8S-501)
