### ISSUE TITLE
Deploying with Kustomize doesn't apply the namespace to URLs

### ISSUE THREAD

**Issue by DClabaut** [redpanda-data/helm-charts#1641]
### What happened?

I'm trying to deploy Redpanda using Kustomize, which loads the Helm chart. I'm using this file, which creates a `redpanda` namespace and deploys the helm chart in it:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redpanda

resources:
  - namespace.yaml

helmCharts:
  - name: redpanda
    repo: "https://charts.redpanda.com"
    releaseName: redpanda
    version: 5.9.19
    valuesFile: values.yaml
```
`values.yaml` can be empty for the purpose of this issue - meaning it's using the `values.yaml` from the chart.

Pods deploy, but fail, as they all try to contact each other as if they were in the `default` namespace, e.g.:
```
WARN  2025-02-10 19:36:01,162 [shard 0:main] cluster - cluster_discovery.cc:262 - Error requesting cluster bootstrap info from {host: redpanda-1.redpanda.default.svc.cluster.local., port: 33145}, retrying. std::__1::system_error (error C-Ares:4, redpanda-1.redpanda.default.svc.cluster.local.: Not found)
```

The thing is... I can't find where in the helm chart is the namespace added to the URLs.

### What did you expect to happen?

Namespace is properly applied throughout the Helm chart.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>
kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redpanda

resources:
  - namespace.yaml

helmCharts:
  - name: redpanda
    repo: "https://charts.redpanda.com"
    releaseName: redpanda
    version: 5.9.19
    valuesFile: values.yaml
```

namespace.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: redpanda
```

values.yaml: empty file

```console
$ kustomize build --enable-helm . | kubectl apply -f -
namespace/redpanda created
serviceaccount/redpanda-console created
configmap/redpanda created
configmap/redpanda-console created
configmap/redpanda-rpk created
secret/redpanda-config-watcher created
secret/redpanda-configurator created
secret/redpanda-sts-lifecycle created
service/redpanda created
service/redpanda-console created
service/redpanda-external created
deployment.apps/redpanda-console created
statefulset.apps/redpanda created
poddisruptionbudget.policy/redpanda created
job.batch/redpanda-configuration created
servicemonitor.monitoring.coreos.com/redpanda created
pod/redpanda-console-test-connection created
pod/redpanda-test-api-status created
pod/redpanda-test-console created
pod/redpanda-test-kafka-nodelete created
pod/redpanda-test-kafka-produce-consume created
pod/redpanda-test-lifecycle created
pod/redpanda-test-pandaproxy-status created
pod/redpanda-test-prometheus-targets created
pod/redpanda-test-rack-awareness created

$ kubectl -n redpanda logs -f pod/redpanda-0 
```

</details>

### Chart Version(s)

5.9.19

### Cloud provider

Google Cloud

JIRA Link: [K8S-503](https://redpandadata.atlassian.net/browse/K8S-503)
