### ISSUE TITLE
`listeners.kafka.external.default.nodePort` not respected

### ISSUE THREAD

**Issue by mattfysh** [redpanda-data/helm-charts#1642]
### What happened?

Sometimes you might need the advertised port to reflect a non-standard networking environment, eg. with kind running locally, you need to provide `extraPortMappings` when setting up the k8s cluster and it cannot be changed later. In this scenario, you might have port 39999 mapped to an ingress router, such as traefik, who then performs SNI-based L5 routing to NodePort services

Unfortunately, the following config does not produce the desired effect - the generated NodePort service attempts to use port 443 which isn't allowed by the k8s controller

```yaml
listeners:
  kafka:
    external:
      default:
        nodePort: 39999
        advertisedPorts: [443]
```

I looked through the templates and can only see the `listener.nodePort` option being used in the LoadBalancer, not the NodePort template

### What did you expect to happen?

Ability to separate physical node port and advertised listener port

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```yaml
statefulset:
  replicas: 1
tls:
  enabled: false
external:
  domain: k.test.unweb
listeners:
  schemaRegistry:
    enabled: false
  http:
    enabled: false
  admin:
    enabled: false
  kafka:
    external:
      default:
        nodePort: 39999
        advertisedPorts: [443]
storage:
  hostPath: /sandbox/rp/storage
  persistentVolume:
    enabled: false

```

</details>

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# redpanda-a662ef66  	cloud-test	1       	2025-02-11 17:51:17.136779 +1000 AEST	deployed	redpanda-5.9.19  	v24.3.3    
```

</details>

### Cloud provider

<details>
kind (local)
</details>
