### ISSUE TITLE
Helm chart with custom namespace creates invalid service addresses

### ISSUE THREAD

**Issue by rrva** [redpanda-data/helm-charts#174]
When using the latest helm chart to install redpanda on kubernetes and using the `--namespace` option, the chart seems to generate invalid service urls containing an extra ".redpanda." level in each hostname.

Here are the steps I needed to make it work in my installation:

1. helm install redpanda redpanda/redpanda --namespace myns --dry-run > redpanda.yaml
2. Search and replace each .svc address to only contain `myns.svc` as the domain part, omit .redpanda.

Also (perhaps unrelated to this), there was no correct services created for each broker, (redpanda-0, redpanda-1, redpanda-2), only a single service called "redpanda".

So I added the following to make brokers find each other:

```
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-0
  namespace: "myns"
  labels:
    helm.sh/chart: redpanda-2.1.7
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "redpanda"
    app.kubernetes.io/component: redpanda
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-0
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-1
  namespace: "myns"
  labels:
    helm.sh/chart: redpanda-2.1.7
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "redpanda"
    app.kubernetes.io/component: redpanda
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-1
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-2
  namespace: "myns"
  labels:
    helm.sh/chart: redpanda-2.1.7
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "redpanda"
    app.kubernetes.io/component: redpanda
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-2
---
```
