### ISSUE TITLE
Configuring ballast_file tuning in helm chart does not create ballast_file

### ISSUE THREAD

**Issue by doganyazar** [redpanda-data/helm-charts#233]
Added the following config in values.yaml file
```
tuning:
  # Creates a "ballast" file so that, if a Redpanda node runs out of space,
  # you can delete the ballast file to allow the node to resume operations and then
  # delete a topic or records to reduce the space used by Redpanda.
  tune_ballast_file: true
  #
  # The path where the ballast file will be created.
  ballast_file_path: "/var/lib/redpanda/data/ballast"
  #
  # The ballast file size.
  ballast_file_size: "1GiB"
```

And I can see that it is reflected in redpanda config map:
```
    rpk:
      enable_usage_stats: false
      overprovisioned: true
      enable_memory_locking: true
      tune_ballast_file: true
      ballast_file_path: /var/lib/redpanda/data/ballast
      ballast_file_size: 1GiB
```
But ballast_file is not created under /var/lib/redpanda/data until I manually run 
`rpk redpanda mode prod && rpk redpanda tune ballast_file`

If this is expected behaviour then it would be nice to have a way to configure prod mode from helm chart directly.
