### ISSUE TITLE
rack awareness: `rack` not set

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#243]
When testing rack awareness on kind, I find that the only configuration applied to `redpanda.yaml` is `enable_rack_awareness: true`, not `rack`.

Steps to reproduce:

1. Define a cluster in the kind.yaml configuration file:

    ```
    cat <<EOF >kind.yaml
      ---
      apiVersion: kind.x-k8s.io/v1alpha4
      kind: Cluster
      nodes:
        - role: control-plane
        - role: worker
        - role: worker
        - role: worker
      EOF
    ```

2. Create the Kubernetes cluster from the configuration file:

    ```
    kind create cluster --config kind.yaml
    ```

3. Annotate the nodes:

    ```
    kubectl annotate node kind-worker kind-worker2 kind-worker3 topology.kubernetes.io/zone=rack1
    ```

4. Enable rack awareness:

    ```yaml
    rackAwareness:
        enabled: true
    serviceAccount:
        create: true
    rbac:
        enabled: true
    ```

5. Deploy the Redpanda cluster:

    ```
    helm repo add redpanda https://charts.redpanda.com/
    helm repo update
    helm upgrade --install redpanda redpanda/redpanda \
    --namespace redpanda --create-namespace \
    --values rack-awareness.yaml
    ```

6. Check the node annotations:

    ```
    kubectl get node \
    -o=custom-columns=NODE:.metadata.name,ZONE:.metadata.annotations."topology\.kubernetes\.io/zone"
    ```
  
    ```
    NODE                 ZONE
    kind-worker        rack1
    kind-worker2      rack1
    kind-worker3      rack1
    ```

7. Check that rack awareness has been enabled and configured on the Redpanda brokers:

    ```bash
    kubectl -ti -n redpanda exec redpanda-0 -c redpanda -- \
    grep 'rack' etc/redpanda/redpanda.yaml
    ```

This shows that only `enable_rack_awareness: true` is configured.

**Comment by JakeSCahill** [comment]
My actual YAML file was misconfigured, causing this issue.

I had this:

```yaml
rackAwareness:
    enabled: true
    serviceAccount:
      create: true
    rbac:
      enabled: true
```

`serviceAccount` and `rbac` should be at the root level.
