### ISSUE TITLE
AttachVolume.Attach failed for volume during k8s upgrade

### ISSUE THREAD

**Issue by ErlendFax** [redpanda-data/helm-charts#246]
After manually triggering a GKE k8s upgrade from `1.23.12-gke.100` to `1.24.7-gke.900` Redpanda had problems getting back up. No producers or consumers were able to reach Redpanda for about 4 min. This has happened a few times before.

**Timeline of events:**
1. Upgrade is triggered in GCP Console
2. One of three Redpanda instances is taken down and placed in its new node, and consumers and producers suddenly can't reach  Redpanda at all
3. K8s logs says `AttachVolume.Attach failed for volume "pvc-123-123-123" ... ` 
4. This goes on for a few minutes before solving itself
5. Same thing happens to the two other Redpanda instances
6. When _all_ moving of instances has been done, consumers and producers are able to connect again.
 
**Thoughts:**
My guess is that the PVC isn't detached correctly when moving over to a new node, or needs more time to get properly detached. One PVC can only be connected to one VM at a time. 

I posted the issue here since volume attachment is something more related resources and infrastructure, but please correct me if my assumptions are wrong. 

Another thing, I don't get why all of Redpanda goes down if only one instance has problems... 🤔 

**Versions:**
- Helm chart: redpanda-2.3.0 
- Redpanda version: v22.2.2

<details>
<summary>
Logs
</summary>

All K8s logs are found here [k8s-logs.txt](https://github.com/redpanda-data/helm-charts/files/10236134/k8s-logs.txt).

All producer logs are found here: [producer-logs.txt](https://github.com/redpanda-data/helm-charts/files/10236321/producer-logs.txt), and they look like this:
```
error writing messages to measurements_l2 (partition 15): kafka.(*Client).Produce: fetch request error: topic partition has no leader (topic=\"measurements_l2\" partition=15)" module=kafka

```

All consumer logs during downtime are found here: [consumer-logs.txt](https://github.com/redpanda-data/helm-charts/files/10236325/consumer-logs.txt), and looks something like this:
```
Crash: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 10.64.2.6:9093
Restarting the consumer in 300ms
Connection error: connect ECONNREFUSED 10.64.2.6:9093
Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.64.2.6:9093
Response Fetch(key: 1, version: 11)
Response SyncGroup(key: 14, version: 3)
Response Heartbeat(key: 12, version: 3)
...
Response Heartbeat(key: 12, version: 3)
Response JoinGroup(key: 11, version: 5)
Response Fetch(key: 1, version: 11)
...
Response Fetch(key: 1, version: 11)
Connection error: connect ECONNREFUSED 10.64.7.7:9093
Connection error: connect ETIMEDOUT 10.64.7.7:9093
...
```
</details>

<details>
<summary>
values.yaml
</summary>

```
image:
  repository: vectorized/redpanda
  tag: v22.2.2

resources:
  cpu:
    cores: 2
    overprovisioned: true
  memory:
    enable_memory_locking: true
    container:
      min: 6.5Gi
      max: 8.0Gi

storage:
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: "ssd-redpanda"

statefulset:
  replicas: 3
  nodeSelector:
    cloud.google.com/gke-nodepool: redpanda-pool-dev
  tolerations:
    - key: "redpanda"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

config:
  cluster:
    enable_idempotence: false
    enable_transactions: false

```
</details>
