### ISSUE TITLE
Console reports custom version

### ISSUE THREAD

**Issue by soudaburger** [redpanda-data/helm-charts#255]
Using the helm chart to deploy both redpanda and the console, the console is reporting the redpanda version as `unknown custom version at least v0.10.2`.

**Comment by JakeSCahill** [comment]
The versioning information comes from the admin API. Redpanda Console seems to disable it by default:

```yaml
redpanda:
  # Redpanda Admin API configuration that enables additional Redpanda-specific features.
  adminApi:
    enabled: false
```
