### ISSUE TITLE
external.addresses only picks up the first value

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#258]
chart version: redpanda-2.4.0

Steps to reproduce:

1. Set `external.addresses` to some IPs (one for each broker).

    ```yaml
    external:
      addressType: ip
      addresses: "203.0.113.3 203.0.113.5 203.0.113.7"
    ```

1. Apply the file to the Helm deployment.

1. Check the `redpanda.yaml` for each broker.

    ```
    kubectl exec redpanda-0 -n redpanda -c redpanda -- cat /etc/redpanda/redpanda.yaml
    ```
    
    ```
    kubectl exec redpanda-1 -n redpanda -c redpanda -- cat /etc/redpanda/redpanda.yaml
    ```
    
    ```
    kubectl exec redpanda-2 -n redpanda -c redpanda -- cat /etc/redpanda/redpanda.yaml
    ```

They all use the same IP address in their`advertised_kafka_api` field.

```yaml
    advertised_kafka_api:
        - address: redpanda-2.redpanda.redpanda.svc.cluster.local.
          port: 9093
          name: internal
        - address: 203.0.113.3
          port: 31092
          name: default
```

The PandaProxy API is also advertising the FQDN of the headless Cluster IP:

```
    advertised_pandaproxy_api:
        - address: redpanda-2.redpanda.redpanda.svc.cluster.local.
          port: 8082
          name: internal
        - address: redpanda-2.redpanda.redpanda.svc.cluster.local.
          port: 30082
          name: default
```
