### ISSUE TITLE
Helm upgrade Redpanda disconnects clients

### ISSUE THREAD

**Issue by ErlendFax** [redpanda-data/helm-charts#287]
(This also happens during GKE Node upgrades).

We run a Redpanda cluster with 3 nodes spun up using Helm. We have 6 topics, ca. 100 partitions, 4 producers and 3 consumers.

**This is what happens:**
1. Starting upgrade with `helm upgrade redpanda redpanda/redpanda -n redpanda -f values-redpanda.yaml`
2. Clients disconnect

Producer (kafka-go) is not able to connect at all, and rapidly logging stuff like this (we might be spamming redpanda too much here, but we shouldn't come to this point at the first place):
```
[kafka-internal] info error writing messages to measurements_l1 (partition 8): kafka.(*Client).Produce: unexpected EOF
...
[kafka-internal] info error writing messages to measurements_l1 (partition 5): kafka.(*Client).Produce: dial tcp 10.64.1.3:9093: connect: connection refused
...
[kafka-internal] info error writing messages to measurements_l1 (partition 13): kafka.(*Client).Produce: dial tcp 10.64.1.3:9093: i/o timeout
...
[kafka-internal] info error writing messages to measurements_l1 (partition 8): kafka.(*Client).Produce: fetch request error: topic partition has no leader (topic="measurements_l1" partition=8)
...
```
 While consumer (kafkajs) loose connection and reconnect a few times during this:
```
 Connection error: connect ECONNREFUSED 10.64.1.3:9093
```
3. They do not reconnect before the full rolling update is complete.

I would expect no to little interruption in both producers and consumers.

I have included the redpanda logs below.

Not familiar with the logs, but it looks like the first node completes the pre-stop sequence in a few short seconds, and is after that marked as down (maybe expected?). After ~ 20 sec it is started up again. This happens for all  three nodes before clients are reconnected.

I was told that long-running transfer of leader and draining etc. could cause this to just kill redpanda, but it looks like the pre-stop is done in a short sec. 

**Expected behaviour:**
1. Starting upgrade
2. Clients has little to no issues with the connection, only using one of the two nodes still up.
5. Upgrade complete.

**Additional info:**

Chart: 2.5.1
App: 22.3.10

<details>
<summary>  values.yaml </summary>

```
image:
  repository: vectorized/redpanda
  tag: v22.3.10

resources:
  cpu:
    cores: 2
    overprovisioned: true
  memory:
    enable_memory_locking: true
    container:
      min: 7.5Gi
      max: 10.0Gi

storage:
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: "ssd-redpanda"

statefulset:
  replicas: 3
  nodeSelector:
    cloud.google.com/gke-nodepool: redpanda-pool-dev
  tolerations:
    - key: "redpanda"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

config:
  cluster:
    enable_idempotence: false
    enable_transactions: false


```
</details>

[downloaded-logs-20230123-130034.txt](https://github.com/redpanda-data/helm-charts/files/10479414/downloaded-logs-20230123-130034.txt) (includes start of upgrade and the next minutes, json format)

_(I initally misread the logs, thats why I renamed the issue)_
