### ISSUE TITLE
Remove redpanda-specific commented-out parameters from values.yaml

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#309]
The last `config` section should be updated to be something like the following:

```
# Expert Config

# This section contains various settings supported by Redpanda that may not work
# correctly in a kubernetes cluster. Changing these settings comes with some risk.
#
# Here be dragons!
#
# This section allows modifying various Redpanda settings not covered in other sections above.
# These values do not pertain to the kubernetes objects created with helm.
# Instead these parameters get passed directly to the Redpanda binary at startup.
# See the following links:
# - https://docs.redpanda.com/docs/cluster-administration/configuration/
# - https://docs.redpanda.com/docs/reference/
config:
  cluster: {}
    # https://docs.redpanda.com/docs/reference/cluster-properties/
  tunable: {}
    # https://docs.redpanda.com/docs/reference/tunable-properties/
  node: {}
    # https://docs.redpanda.com/docs/reference/node-properties/
```

I think for these redpanda-specific values maybe we should just delete them and point the user to documentation. I think it makes sense to have detailed documentation in the form of comments in this file for helm-related parameters, but the ones that are just passed to redpanda are likely to not be touched much by us during testing, and so any updates on the Redpanda side will be much less likely to result in an update here.
