### ISSUE TITLE
Ensure passing a values.yaml without `listeners` section works

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#311]
There was a report today regarding an issue with `advertised_kafka_api` being set to this:
```
{"name":"default","address":"","port":31092}
```

This was with a heavily customized values.yaml, and the listeners section looked like this:
```
listeners:
  # Admin API listener
  admin:
    port: 9644
    tls:
      enabled: false
  # Kafka API listeners
  kafka:
    port: 9092
    tls:
      enabled: false
  http:
    enabled: true
    port: 8082
    kafkaEndpoint: default
    tls:
      enabled: false
  # RPC listener
  rpc:
    port: 33145
    tls:
      enabled: false
  # Schema registry listeners
  schemaRegistry:
    enabled: true
    port: 8081
    kafkaEndpoint: default
    tls:
      enabled: false
```

One immediate issue I see is that, with the above config, it's likely that http and schema registry endpoints would not work. Since they are themselves Kafka clients, they must access the Kafka endpoint. This is given by `kafkaEndpoint`, which doesn't exist in the above config.

The other issue that advertised listeners depend on having at least one external listener in order to be properly set (see [here](https://github.com/redpanda-data/helm-charts/blob/4b53835bc46a5800c1bb442a161538da056b86de/charts/redpanda/templates/statefulset.yaml#L93-L117)).

We should ensure users can customize the listeners, but better ensure they won't get into a state where things don't work.
