### ISSUE TITLE
Add imagePullSecrets to redpanda chart

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/helm-charts#444]
### What would you like to be added?

For users that want to deploy the Helm chart in an air-gapped environment will need to pull the Redpanda image from an internal image repository, e.g:

```yaml
# Redpanda settings
image:
  repository: http://docker.artifactory.local.com/vectorized/redpanda
  tag: v23.1.7
  pullPolicy: IfNotPresent
```

If the internal repository requires a username and password to authenticate then the Helm chart deployment currently fails:

```
Failed to pull image "http://docker.artifactory.local.com/vectorized/redpanda:v23.1.7": rpc error: code = Unknown desc = failed to pull and unpack image "http://docker.artifactory.local.com/vectorized/redpanda:v23.1.7": failed to resolve reference "http://docker.artifactory.local.com/vectorized/redpanda:v23.1.7": failed to authorize: failed to fetch anonymous token: unexpected status: 401
```

The Helm chart should have the ability to pass authentication credentials to the image repository.

### Why is this needed?

For air-gapped deployments that require authentication to download the Redpanda image from an internal repository.

**Comment by alejandroEsc** [comment]
If you are installing this on a kubernetes cluster that is airgapped, does your k8s instance not have access to the docker registry? My concern is that I'm not sure if its safe to pass the registry creds in this fashion, we could do something like this: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ but if you have any additional recommendations we can definitely consider our options.

**Comment by carlosfwrk** [comment]
@alejandroEsc, I think that we need with redpanda chart (to use a secret with credentials) is already solved in console chart.

We need something like this:
```shell
$ helm show values redpanda/console | grep imagePullSecrets -A 4 -B 14
```
```yaml
# -- Redpanda Console Docker image settings.
image:
  registry: docker.artifactory.local.com
  # -- Docker repository from which to pull the Redpanda Docker image.
  repository: vectorized/console
  # -- The imagePullPolicy.
  pullPolicy: IfNotPresent
  # -- The Redpanda Console version.
  # See DockerHub for:
  # [All stable versions](https://hub.docker.com/r/redpandadata/console/tags)
  # and [all unstable versions](https://hub.docker.com/r/redpandadata/console-unstable/tags).
  # @default -- `Chart.appVersion`
  tag: "v23.1.7"

imagePullSecrets:
- name: regcred
# -- Override `console.name` template.
nameOverride: ""
# -- Override `console.fullname` template.
fullnameOverride: ""
```
