### ISSUE TITLE
Allow setting the priorityClassName/topologySpreadConstraints in the console helm chart through the values.yaml

### ISSUE THREAD

**Issue by rubenvw-ngdata** [redpanda-data/helm-charts#460]
### What would you like to be added?

Allow to set priorityClassName and topologySpreadConstraints through the values.yanl similar to how that is available for affinities in the redpanda console chart (https://github.com/redpanda-data/helm-charts/tree/main/charts/console).

### Why is this needed?

It allows me to run redpanda console in a HA setup.

**Comment by alejandroEsc** [comment]
Do you mean allow your own `topologySpreadConstraints` stanza, for priority class name we have

```
{{- if .Values.statefulset.priorityClassName }}
      priorityClassName: {{ .Values.statefulset.priorityClassName }}
{{- end }}
```
so you can already change this?

**Comment by rubenvw-ngdata** [comment]
@alejandroEsc Sorry that I was not clear on this, but I am talking about the redpanda console chart (https://github.com/redpanda-data/helm-charts/tree/main/charts/console)
I will update the text accordingly.

**Comment by alejandroEsc** [comment]
@rubenvw-ngdata thank you for clearing that up!

**Comment by joejulian** [comment]
I believe this was fixed by #467. @rubenvw-ngdata Can you please confirm that this satisfies your request?

**Comment by rubenvw-ngdata** [comment]
@joejulian I think it is not. The fix is on the redpanda chart, my request is for the redpanda console chart.

**Comment by joejulian** [comment]
This is already exposed in the values as the `affinity` key. This is a bare include: https://github.com/redpanda-data/helm-charts/blob/7ddcd331eba27aaed36140de7d6170bcc855b1f0/charts/console/templates/deployment.yaml#L257-L259

mytopo.yaml
```
affinity:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: NotIn
            values:
            - zoneC
```

if you're setting these via the redpanda chart (console subchart), simply add the console key in front of it, ie:
```
console:
  affinity:
    ....
```
