### ISSUE TITLE
Cross region replication between clusters with TLS

### ISSUE THREAD

**Issue by soudaburger** [redpanda-data/helm-charts#481]
### What happened?

I essentially would like to have two separate GKE clusters, both with TLS configured.  I have the networking connectivity piece configured so that each cluster will be reachable from the other over ClusterIP (Multicluster Ingress).

```bash
rpk topic list --brokers redpanda.kafka.svc.clusterset.local:9094 --tls-enabled

unable to request metadata: unable to dial: x509: certificate signed by unknown authority
```

Currently getting the above.

Is there a flag to ignore verifying TLS signatures?  I'm willing to accept that risk since both clusters would be self-signing their own certificates and CAs.

Otherwise I figure I essentially have two options, neither of which seems ideal:
1. Use another tool to copy the certificates/keys between the clusters.
2. Potentially leverage `cert-manager` to issue the CA and certificates, but those would still be separate CA certificates between the clusters.

### What did you expect to happen?

I would like to be able to simply trust the connection to allow the connection through, but I don't see a way to currently do that.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```yaml
external:
  enabled: true
  type: NodePort
  domain: kafka.svc.clusterset.local
tls:
  certs:
    # Set the `caEnabled` flag to `true` only for Certificates
    # that are not authenticated using public authorities.
    internal:
      caEnabled: true
    external:
      caEnabled: true
```

TLS is also configured on each listener port with the necessary config.

### Chart Version(s)

Chart Version: `4.0.13`

### Cloud provider

GKE autopilot

**Comment by soudaburger** [comment]
Ok, while I was unable to avoid verifying TLS certificates, I _was_ successfully able to:

1. Generate a self-signed CA
2. Generate self-signed server certificate with Kafka
3. Used `*.$service.svc.clusterset.local` as a dns_name on my certificate (To support multi-cluster ingress on GKE)
4. Used `*.redpanda.$namespace.svc.cluster.local` as a dns_name on my certificate (To support internal comms, bootstrapping.


Used the following modified values (not complete):
```yaml
listeners:
  kafka:
    tls:
      enabled: true
      cert: external
    external:
      default:
        tls:
          enabled: true
          cert: external
tls:
  certs:
    external:
      secretRef:
        name: my-secret-in-k8s-that-already-has-tls-certs
      caEnabled: true
  enabled: true
  ```

This allowed me to bootstrap the kafka config, using custom certificates that will allow me to reach these servers over the multi-cluster ingress once I figure out how to seed a second set of nodes from the original set.
