### ISSUE TITLE
Support basic authentication for proxy and schema registry

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/helm-charts#499]
### What would you like to be added?

Add the ability to configure basic authentication for the HTTP proxy and schema registry.

```yaml
pandaproxy:
  pandaproxy_api:
  - address: "localhost"
    port: 8082
    authentication_method: http_basic

schema_registry:
  schema_registry_api:
    address: "localhost"
    port: 8081
    authentication_method: http_basic
```

https://docs.redpanda.com/docs/manage/security/authentication/#configure-basic-authentication

### Why is this needed?

To give the user the choice between using mTLS and basic authentication.
