### ISSUE TITLE
configwatcher sidecar resources not working

### ISSUE THREAD

**Issue by ngalanis930** [redpanda-data/helm-charts#557]
### What happened?

I have installed redpanda chart version redpanda-4.0.42
After enabling configWatch and defining resource requests and limits in values.yaml the sidecar container seems to ignore that. 

### What did you expect to happen?

resource limits and requests should be applied

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

```
  sideCars:
    configWatcher:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 150Mi
```

### Anything else we need to know?

It worked out for me after adding the below snippet In statefulset.yaml between lines 333 and 334:
      
```
 resources:
 {{- toYaml .Values.statefulset.sideCars.configWatcher.resources | nindent 12 }}
```
Hope to see that change on the next chart version

### Which are the affected charts?

Redpanda

### Chart Version(s)

chart version redpanda-4.0.42

### Cloud provider

Managed Kubernetes cluster
