### ISSUE TITLE
ServiceMonitor does not include tlsConfig

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#568]
### What happened?

The ServiceMonitor resource does not include [`tlsConfig` settings](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Endpoint) for the endpoints, resulting in the following error:

![2023-06-29_12-17-16](https://github.com/redpanda-data/helm-charts/assets/45230295/79c056b1-d4a9-4460-9805-4672b5e3f069)

### What did you expect to happen?

The ServiceMonitor deployed by the Redpanda Helm chart should include all necessary configuration to work out of the box.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Add charts and deploy cert-manager:

```
helm repo add redpanda https://charts.redpanda.com                                                                       
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager  --set installCRDs=true --namespace cert-manager  --create-namespace
```

Install Prometheus Operator CRDs:

```
LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
curl -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/${LATEST}/bundle.yaml | kubectl create -f -
```

Deploy Redpanda with monitoring enabled (I was using kind):

```
export DOMAIN=customredpandadomain.local && \                                                                            
helm repo add redpanda https://charts.redpanda.com/
helm repo update
helm install redpanda redpanda/redpanda \
  --namespace redpanda \
  --create-namespace \
  --set external.domain=${DOMAIN} \
  --set statefulset.initContainers.setDataDirOwnership.enabled=true \
--set monitoring.enabled=true
```

Create RBAC rules for Prometheus:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
```

Deploy Prometheus:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: redpanda
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/name: redpanda
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```

Wait until Prometheus is ready:

```
kubectl get -n default prometheus prometheus -w
```

Deploy NodePort to access Prometheus:

```
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
```

Forward ports:

```
kubectl port-forward svc/prometheus 9090       
```

### Which are the affected charts?

Redpanda

### Chart Version(s)

redpanda-4.0.48

### Cloud provider

local kind cluster
