### ISSUE TITLE
When reconfiguring TLS with different CA Issuer, the reference in redpanda-default-root-certificate doesn't change

### ISSUE THREAD

**Issue by angst-storm** [redpanda-data/helm-charts#591]
### What happened?

I have rendered helm chart template with settings in values changing CA Issuer to sign default certificates. The reference to CA Issuer is correct in redpanda-default-cert, but incorrect in redpanda-default-root-certificate. Because of this, the second certificate cannot become READY and redpanda does not get up

helm command:
```console
helm template redpanda \
	--values values.yaml \
	--repo https://charts.redpanda.com \
	--namespace redpanda \
	redpanda > redpanda.yaml
```

values.yaml:
```yaml
tls:
    enabled: true
    certs:
        default:
            issuerRef:
                name: ca-issuer
                kind: ClusterIssuer
            caEnabled: false
external:
    domain: "redpanda.redpanda.svc.cluster.local"
```

issuerRef in redpanda-default-cert in redpanda.yaml 👍:
```yaml
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
```

issuerRef in redpanda-default-cert in redpanda.yaml:
```yaml
  issuerRef:
    name: redpanda-default-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
```

certificate statuses:
![image](https://github.com/redpanda-data/helm-charts/assets/77481770/7fd3f42b-b06a-41b0-9308-ad770eb30791)

### What did you expect to happen?

I expected the issuerRef of redpanda-default-root-certificate to be the same as redpanda-default-cert.
[This article](https://docs.redpanda.com/docs/manage/kubernetes/security/kubernetes-tls/#use-a-public-ca-certificate) does not say this directly, but the certificate is expected to be READY

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm template redpanda \
	--values values.yaml \
	--repo https://charts.redpanda.com \
	--namespace redpanda \
	redpanda > redpanda.yaml
```
values.yaml:
```yaml
statefulset:
    replicas: 1
auth:
    sasl:
        enabled: true
        users:
            - name: admin
              password: password
tls:
    enabled: true
    certs:
        default:
            issuerRef:
                name: ca-issuer
                kind: ClusterIssuer
            caEnabled: false
external:
    domain: "redpanda.redpanda.svc.cluster.local"
```
</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

4.0.55

</details>

### Cloud provider

<details>

</details>
