### ISSUE TITLE
Not able to pull image 

### ISSUE THREAD

**Issue by VipulZopSmart** [redpanda-data/helm-charts#652]
Team, I'm trying to install redpanda-console helm chart on the Minikube. I've followed this: https://github.com/redpanda-data/helm-charts/tree/main/charts/console
After deploying the helm chart, getting this error: 
```
Failed to load logs: container "console" in pod "red-test-console-858d64b4cb-fnxp9" is waiting to start: trying and failing to pull image
Reason: BadRequest (400)
```

values.yaml
```
affinity: {}
annotations: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
configmap:
  create: true
console:
  config:
    kafka:
      brokers:
      - xyz:9092
      clientId: redpanda-console
      sasl:
        enabled: true
        mechanism: PLAIN
        username: xyz
      tls:
        enabled: true
deployment:
  create: true
extraContainers: []
extraEnv: []
extraEnvFrom: []
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  registry: docker.redpanda.com
  repository: redpandadata/console
  tag: ""
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 99
  runAsUser: 99
priorityClassName: ""
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources: {}
secret:
  create: true
  enterprise: {}
  kafka:
    saslPassword: xyz
  login:
    github: {}
    google: {}
    jwtSecret: ""
    oidc: {}
    okta: {}
  redpanda:
    adminApi: {}
secretMounts: []
securityContext:
  runAsNonRoot: true
service:
  annotations: {}
  port: 8080
  targetPort: null
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
tolerations: []
topologySpreadConstraints: {}
```
