### ISSUE TITLE
Applying config changes on upgrade

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#668]
I'm spinning up a cluster:

```
helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace --wait --debug --set tls.enabled=false -f tmp.yaml
```

Were tmp.yaml is:
```
config:
  cluster:
    delete_retention_ms: 50000
  tunable:
    kafka_batch_max_bytes: 1000000
```

This works (the two above values are set as expected). Then I change these values to something else and run the above upgrade command again, but the values don't get updated.
