### ISSUE TITLE
Helm reconciliation is failling with argocd applications

### ISSUE THREAD

**Issue by Jojoooo1** [redpanda-data/helm-charts#672]
### What happened?

After installing CRDs, operator and Cluster the HelmReleaseReconciler. Logs is showing:

```json
{"level":"info","ts":"2023-08-18T23:31:56.029Z","msg":"HelmRelease 'redpanda/redpanda' is not ready","controller":"redpanda","controllerGroup":"cluster.redpanda.com","controllerKind":"Redpanda","Redpanda":{"name":"redpanda","namespace":"redpanda"},"namespace":"redpanda","name":"redpanda","reconcileID":"aff33c34-6fd6-4f37-ae1e-0a02aa118f25"}
{"level":"info","ts":"2023-08-18T23:31:56.034Z","logger":"RedpandaReconciler.Reconcile","msg":"reconciliation finished in 12.133049ms, next run in 10s","controller":"redpanda","controllerGroup":"cluster.redpanda.com","controllerKind":"Redpanda","Redpanda":{"name":"redpanda","namespace":"redpanda"},"namespace":"redpanda","name":"redpanda","reconcileID":"aff33c34-6fd6-4f37-ae1e-0a02aa118f25"}
{"level":"info","ts":"2023-08-18T23:32:06.035Z","logger":"RedpandaReconciler.Reconcile","msg":"Starting reconcile loop","controller":"redpanda","controllerGroup":"cluster.redpanda.com","controllerKind":"Redpanda","Redpanda":{"name":"redpanda","namespace":"redpanda"},"namespace":"redpanda","name":"redpanda","reconcileID":"da06e1f2-d16a-4432-9ae1-89b5534e919f"}
{"level":"info","ts":"2023-08-18T23:32:06.035Z","logger":"RedpandaReconciler.createHelmReleaseFromTemplate","msg":"SHA of values file to use: 52BDx6OJLMAIR0qaM1FLW2pATqHJU2s6r_FfoocwHP4=","controller":"redpanda","controllerGroup":"cluster.redpanda.com","controllerKind":"Redpanda","Redpanda":{"name":"redpanda","namespace":"redpanda"},"namespace":"redpanda","name":"redpanda","reconcileID":"da06e1f2-d16a-4432-9ae1-89b5534e919f"}

spec version is different
```

### What did you expect to happen?

Cluster should be deployed.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

clone https://github.com/Jojoooo1/argo-deploy

```
make start-k3s # should take a few minutes.
```

Open argo dashboard at : http://argo.local.com.br and use the creds showed in the logs.
Then sync the followings ArgoCD applications redpanda-crds, redpanda-operator and redpanda-cluster

### Which are the affected charts?

Operator

### Chart Version(s)

I am using the followings ArgoCD applications:

https://github.com/Jojoooo1/argo-deploy-applications-infra/blob/main/base/applications-infra/redpanda/crds/kustomization.yaml
https://github.com/Jojoooo1/argo-deploy-applications-infra/blob/main/base/applications-infra/redpanda/operator/redpanda-operator-app.yaml
https://github.com/Jojoooo1/argo-deploy-applications-infra/blob/main/base/applications-infra/redpanda/cluster/cluster.yaml

### Cloud provider

<details>

</details>

JIRA Link: [K8S-55](https://redpandadata.atlassian.net/browse/K8S-55)

[K8S-55]: https://redpandadata.atlassian.net/browse/K8S-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Jojoooo1** [comment]
starting to work after creating the following rbac:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-crd
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-controller-operator-list-crd
subjects:
- kind: ServiceAccount
  name: redpanda-controller-operator
  namespace: redpanda
roleRef:
  kind: ClusterRole
  name: list-crd
  apiGroup: rbac.authorization.k8s.io
```

**Comment by alejandroEsc** [comment]
So to test out: 
```
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef:
    timeout: 1m0s
  
  clusterSpec:
    external:
      domain: redpanda.local
    statefulset:
      PodAntiAffinity:
        type: custom
        custom:
          rule: ""
      initContainers:
        setDataDirOwnership:
          enabled: true
```
