### ISSUE TITLE
Include protocol options for various connection types

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#68]
The bitnami chart includes the following in its `auth` section:
```yaml
auth:
  clientProtocol: plaintext
  externalClientProtocol: plaintext
  interBrokerProtocol: plaintext
```
