### ISSUE TITLE
Deploying kminion fails as a subchart

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#706]
### What happened?

I am trying to deploy kminion as a subchart. kubectl and helm version as following:

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T00:50:44Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.1400", GitCommit:"4eb57372b0f0ac0023caca078161b75185febeef", GitTreeState:"clean", BuildDate:"2023-06-05T09:29:48Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

It fails with the following:

```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "redpanda-uts-kminion" namespace: "redpanda-uts" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

The k8s cluster has:

```
k api-versions | grep policy 
policy/v1
```

Helm templating generates this following:

```
---
# Source: redpanda/charts/kminion/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: redpanda-uts-kminion
  namespace: "redpanda-uts"
  labels:
    helm.sh/chart: kminion-0.12.0
    app.kubernetes.io/name: kminion
    app.kubernetes.io/instance: redpanda-uts
    app.kubernetes.io/version: "v2.2.5"
    app.kubernetes.io/managed-by: Helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kminion
      app.kubernetes.io/instance: redpanda-uts
```

I played around with a _helpers.tpl file in the parent chart, and i was lucky to be able to override the helper function: https://github.com/redpanda-data/helm-charts/blob/5029771028f0354d31ce70a69981f81c5da8b4d8/charts/kminion/templates/_helpers.tpl#L118-L124

What i found was:

```
Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget"  was always evaluating to false, regardless my cluster version.
only
.Capabilities.APIVersions.Has "policy/v1" could evaluate correctly
i debug printed the {{ .Capabilities.APIVersions }} and it resulted in:
[v1 admissionregistration.k8s.io/v1 admissionregistration.k8s.io/v1alpha1 admissionregistration.k8s.io/v1beta1 internal.apiserver.k8s.io/v1alpha1 apps/v1 apps/v1beta1 apps/v1beta2 authentication.k8s.io/v1 authentication.k8s.io/v1alpha1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2 autoscaling/v2beta1 autoscaling/v2beta2 batch/v1 batch/v1beta1 certificates.k8s.io/v1 certificates.k8s.io/v1beta1 certificates.k8s.io/v1alpha1 coordination.k8s.io/v1beta1 coordination.k8s.io/v1 discovery.k8s.io/v1 discovery.k8s.io/v1beta1 events.k8s.io/v1 events.k8s.io/v1beta1 extensions/v1beta1 flowcontrol.apiserver.k8s.io/v1alpha1 flowcontrol.apiserver.k8s.io/v1beta1 flowcontrol.apiserver.k8s.io/v1beta2 flowcontrol.apiserver.k8s.io/v1beta3 networking.k8s.io/v1 networking.k8s.io/v1alpha1 networking.k8s.io/v1beta1 node.k8s.io/v1 node.k8s.io/v1alpha1 node.k8s.io/v1beta1 policy/v1 policy/v1beta1 rbac.authorization.k8s.io/v1 rbac.authorization.k8s.io/v1beta1 rbac.authorization.k8s.io/v1alpha1 resource.k8s.io/v1alpha2 scheduling.k8s.io/v1alpha1 scheduling.k8s.io/v1beta1 scheduling.k8s.io/v1 storage.k8s.io/v1beta1 storage.k8s.io/v1 storage.k8s.io/v1alpha1 apiextensions.k8s.io/v1beta1 apiextensions.k8s.io/v1]
```

It seems like a bug in helm.
https://helm.sh/docs/chart_template_guide/function_list/#capabilitiesapiversionshas + https://helm.sh/docs/chart_template_guide/builtin_objects/
definitely documents that one could include the resource name, but it looks like in reality. it is not working as expected.

Would you mind changing the template function to only check without the resource name, eg.: `.Capabilities.APIVersions.Has "policy/v1"` ? Meanwhile i will be happy with my workaround of overriding the function in the parent chart.

### What did you expect to happen?

kminion should have deployed as a subchart without modification mentioned above.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>
