### ISSUE TITLE
Manually setting advertised addresses not possible due to incorrect tpl

### ISSUE THREAD

**Issue by Scarjit** [redpanda-data/helm-charts#711]
### What happened?

Im currently trying to setup an HA cluster using Redpanda as a subchart to our chart (https://github.com/united-manufacturing-hub/united-manufacturing-hub).
Our cluster is running using 3 replicas and internal traffic to the redpanda pods works fine.

When i however try to connect externally, i get an error from sarama kafka, hinting that the advertised hosts are incorrect (it tries to connect to the kubernetes internal URL).
I therefore try to set the addresses in the values.yaml.

### What did you expect to happen?

It should install and set the advertised hosts correctly.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

Error:
```console
Error: INSTALLATION FAILED: template: united-manufacturing-hub/charts/redpanda/templates/statefulset.yaml:120:23: executing "united-manufacturing-hub/charts/redpanda/templates/statefulset.yaml" at <include "advertised-host" (mustMerge $tmplVals (dict "port" $port))>: error calling include: template: united-manufacturing-hub/charts/redpanda/templates/_helpers.tpl:537:12: executing "advertised-host" at <tpl (.values.external.domain | default "") $>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: : "BasePath" is not a value
```

Values:
```yaml
  redpanda:
	statefulset:
	  replicas: 3
	  updateStrategy:
		type: RollingUpdate
	  budget:
		maxUnavailable: 1
	resources:
	  cpu:
		cores: 5
		overprovisioned: true
	  memory:
		enable_memory_locking: true
		container:
		  max: 8Gi
  
	storage:
	  persistentVolume:
		enabled: true
		size: 700Gi
  
	config:
	  cluster:
		auto_create_topics_enabled: true
		log_compression_type: zstd
	  tunable:
		default_topic_partitions: 6
		retention_bytes: None
		delete_retention_ms: 604800000
		default_topic_replications: 3
	external:
	  type: LoadBalancer
	  addresses:
		- 10.1.2.42
		- 10.1.2.43
		- 10.1.2.44
		- 10.1.2.45
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

Tested on redpanda-3.0.9 and redpanda-5.3.3

</details>

### Cloud provider

<details>
 None, setup using k8s on bare-metal
</details>
