### ISSUE TITLE
Create users listed in `auth.sasl.users`

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#73]
```yaml
# Authentication
auth:
  #
  # SASL configuration
  sasl:
    enabled: false
    # user list
    # TODO create user at startup: https://github.com/redpanda-data/helm-charts/issues/73
    users:
    - name: admin
      # If password isn't given, then the secretName must point to an already existing secret
      # Work in progress! secretName is not yet used (planned for v2 release)
      # passwordSecret: adminPassword
```
Expand details of each entry in `users` list, possibly pointing to a secret for the user password.
