### ISSUE TITLE
`auth.tls.certs` remaining tasks

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#74]
```yaml
# Authentication
auth:
  #
  # TLS configuration
  tls:
    # Enable global TLS, which turns on TLS by default for all listeners
    # If enabled, each listener must set a certificate name (ie. listeners.<group>.<listener>.tls.cert)
    # If disabled, listeners may still enable TLS individually (see listeners.<group>.<listener>.tls.enabled)
    enabled: false
    # list all certificates below, then reference a certificate's name in each listener (see listeners.<listener name>.tls.cert)
    # TODO consider switching certs to list
    certs:
      # This is the certificate name that is used to associate the certificate with a listener
      # See listeners.<listener group>.tls.cert for more information
      # TODO add custom cert support: https://github.com/redpanda-data/helm-charts/pull/51
      kafka:
        # issuerRef:
        #   name: redpanda-cert1-selfsigned-issuer
        # The caEnabled flag determines whether the ca.crt file is included in the TLS mount path on each Redpanda pod
        # TODO remove caEnabled (rely on requireClientAuth): https://github.com/redpanda-data/helm-charts/issues/74
        caEnabled: true
        # duration: 43800h
      rpc:
        caEnabled: true
      admin:
        caEnabled: true
      proxy:
        caEnabled: true
      schema:
        caEnabled: true
```
- [ ] remove `caEnabled`
- [ ] consider switching from map to list/array
