### ISSUE TITLE
Pod selector overlap

### ISSUE THREAD

**Issue by ArturKokoszka** [redpanda-data/helm-charts#749]
### What happened?

We experienced frequent problems with connection to redpanda. It seems that from time to time 2 pods appear:

```
NAME                           READY   STATUS      RESTARTS   AGE
redpanda-0                     2/2     Running     0          22h
redpanda-configuration-x57xp   0/1     Completed   0          17s
redpanda-post-upgrade-kk56m    0/1     Completed   0          11s
```

and they have same selector labels as the main `redpanda-0` pod, so svc sends traffic to them instead of `redpanda-0`.

```
k get svc/redpanda-external -o yaml | grep -i -A 2 selector:
  selector:
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/name: redpanda
```

To fix, it seems that change of labels of `redpanda-configuration` and `redpanda-post-upgrade` is required.

### What did you expect to happen?

To have the traffic directed to `redpanda-0` instead of the other pods.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ k get svc/redpanda-external -o yaml | grep -i -A 2 selector:
#  selector:
#    app.kubernetes.io/instance: redpanda
#    app.kubernetes.io/name: redpanda
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

Redpanda helm chart version: 5.4.7 (same was on 4.0.53).

</details>

### Cloud provider

<details>

Azure, Kubernetes 1.26

</details>
