### ISSUE TITLE
Make external listener `subdomain` parameter optional

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#76]
```yaml
listeners:
  kafka:
    all:
    - address: $(POD_IP)
      name: kafka
      port: 9092
      external:
        enabled: false
        subdomain: "streaming.rockdata.io"
```
See #56 .
