### ISSUE TITLE
TLS Multiple Issuers

### ISSUE THREAD

**Issue by Taranasaur** [redpanda-data/helm-charts#793]
### What happened?

When deploying using multiple issuers e.g. in values:

```
    bus-lab-kafka:
      issuerRef:
        name: bus-kafka-root-issuer
        kind: ClusterIssuer
      secretRef: {}
      caEnabled: true
    bus-lab-admin:
      issuerRef:
        name: bus-admin-root-issuer
        kind: ClusterIssuer
      secretRef: {}
      caEnabled: true
```

The readiness probe fails as "rpk cluster health" will use a client cert generated to interact with the kafka service but not that used for admin:

```
rpk:
    kafka_api:
        brokers:
            - lab-bus-0.lab-bus.lab-bus.svc.cluster.local.:9091
            - lab-bus-1.lab-bus.lab-bus.svc.cluster.local.:9091
            - lab-bus-2.lab-bus.lab-bus.svc.cluster.local.:9091
        tls:
            key_file: /etc/tls/certs/lab-bus-client/tls.key
            cert_file: /etc/tls/certs/lab-bus-client/tls.crt
            ca_file: /etc/tls/certs/bus-lab-kafka/ca.crt
    admin_api:
        addresses:
            - lab-bus-0.lab-bus.lab-bus.svc.cluster.local.:9644
            - lab-bus-1.lab-bus.lab-bus.svc.cluster.local.:9644
            - lab-bus-2.lab-bus.lab-bus.svc.cluster.local.:9644
        tls:
            key_file: /etc/tls/certs/lab-bus-client/tls.key  <<<<<<<<<<<
            cert_file: /etc/tls/certs/lab-bus-client/tls.crt <<<<<<<<<<
            ca_file: /etc/tls/certs/bus-lab-admin/ca.crt
```

### What did you expect to happen?

The previous charts (e.g 5.0.7) the extra flags for admin certs were passed with the rpk command

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
    bus-lab-kafka:
      issuerRef:
        name: bus-kafka-root-issuer
        kind: ClusterIssuer
      secretRef: {}
      caEnabled: true
    bus-lab-admin:
      issuerRef:
        name: bus-admin-root-issuer
        kind: ClusterIssuer
      secretRef: {}
      caEnabled: true
```

</details>

### Chart Version(s)

<details>

5.6.X

### Cloud provider

<details>

</details>
