### ISSUE TITLE
`serviceAccount` and `fsGroup` connection

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#81]
Look into how `serviceAccount` and `fsGroup` are related.

```yaml
# TODO how does creating a service account impact fsGroup?
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
```

```yaml
statefulset:
  # When using persistent storage the volume will be mounted as root. In order for redpanda to use the volume
  # we must set the fsGroup to the uid of redpanda, which is 101
  podSecurityContext:
    fsGroup: 101
    # runAsNonRoot: true
    # runAsUser: 1000
```
