### ISSUE TITLE
HelmRelease resource ownerRef

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#818]
### What would you like to be added?

I would love it if the HelmRelease resource created by the operator's "redpanda" CRD would create k8s ownerReferences for all resources it creates.

### Why is this needed?

For better GitOps compatibility.
For example, I deploy the "redpanda" yaml as part of an ArgoCD application (a custom helm chart), but currently all I can see is the HelmRelease and HelmRepository resources, and not any of the actual resources they manage (which will be really great to see for debugging, monitoring, and management purposes)
![image](https://github.com/redpanda-data/helm-charts/assets/11724502/615c6d03-dc6b-4e20-a846-b77a5d10b53c)

I attempted to manually tinker with this for testing, added the following "ownerReferences" field to the statefulset created by the helm release:
```
  ownerReferences:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    blockOwnerDeletion: true
    controller: true
    kind: HelmRelease
    name: redpanda
    uid: b1b86229-1f47-4deb-a15a-fb373f8e863a
```
And viola, it appears on ArgoCD:
![image](https://github.com/redpanda-data/helm-charts/assets/11724502/f5943f7b-3b91-4932-a07f-0c0cf638f35c)

On the one side it's great, on the other, I can't manage this as the resources are managed by the operator and the UID is generated.
So, if you could implement this on your side, it would be really helpful 🙏🏼
