### ISSUE TITLE
external-dns configuration from operator does not trickle down to HelmRelease

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#819]
### What happened?

Attempting to configure external-dns integration (by following your [docs](https://docs.redpanda.com/current/manage/kubernetes/networking/configure-external-access-loadbalancer/))

The external-dns configuration from the operator resource does not apply to the helmRelease resource
I tried adding it manually, and it works, so it’s probably only a bug on the operator side.

### What did you expect to happen?

I expected the "externalDns" field to apply to the generated helmRelease

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

 I pushed the following yaml:
```apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    external:
      enabled: true
      type: LoadBalancer
      domain: perf-redpanda.linode.csi.akadns6.net
      externalDns:
        enabled: true
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
```
But the generated HelmRelease resource is:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chart:
    spec:
      chart: redpanda
      interval: 1m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redpanda-repository
        namespace: redpanda
      version: '*'
  interval: 30s
  timeout: 15m0s
  upgrade:
    remediation:
      retries: 1
      strategy: rollback
  values:
    external:
      domain: perf-redpanda.linode.csi.akadns6.net
      enabled: true
      type: LoadBalancer
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
```

Notice - externalDns field does not trickle down to it!

### Anything else we need to know?

I also expected the operator to recognize my manual change of the resource and overwrite it (although it's good it didn't in this case, but I think it's an important role for the operator to reconcile)

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```
operator chart version - 0.3.24
redpanda chart version - 5.6.25
```

</details>

### Cloud provider

<details>
Linode
</details>
