### ISSUE TITLE
Configmap dials may cause startup problems, tests needed.

### ISSUE THREAD

**Issue by alejandroEsc** [redpanda-data/helm-charts#822]
### What would you like to be added?

Testing is needed to avoid having issues with configmap (redpanda.yaml) templating. 

### Why is this needed?

The issue here is that if there is a problem with the templating it will cause issues with the init containers and not allow redpanda installation to occur, e.g., a instllation failed with the following configuration:

```
auth:
  sasl:
    enabled: true
    secretRef: some-users
    users: []
external:
  domain: <redacted>
  enabled: true
  externalDns:
    enabled: true
  type: LoadBalancer
statefulset:
  initContainers:
    setDataDirOwnership:
      enabled: true
tls:
  certs:
    default:
      caEnabled: false
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-production
```

The above failed becuase of indentation issue with the redpanda.yaml file, truststore_file: "some/path" had 6 spaces instead of 4. 

JIRA Link: [K8S-69](https://redpandadata.atlassian.net/browse/K8S-69)

[K8S-69]: https://redpandadata.atlassian.net/browse/K8S-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
