### ISSUE TITLE
TLS certificates with existing cert-manager issuer broken

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#829]
### What happened?

Trying to follow your docs to generate public CA certificates using our existing cert-manager clusterIssuer
https://docs.redpanda.com/current/manage/kubernetes/security/kubernetes-tls/#use-a-public-ca-certificate

HelmRelease is failing, looking into the log of the statefulset pods, I see the “tuning” init container is failing with error:
unable to load config: unable to yaml decode /etc/redpanda/redpanda.yaml: yaml: line 133: mapping values are not allowed in this context

### What did you expect to happen?

I expected redpanda to produce tls certificates with my existing cert-manager clusterIssuer

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Operator chart is deployed with the default values.

Here is my deployed redpanda yaml:

```yaml
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-512
        secretRef: redpanda-superusers
        users: []
    external:
      domain: perf-redpanda.linode.csi.akadns6.net
      enabled: true
      externalDns:
        enabled: true
      type: LoadBalancer
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
    tls:
      certs:
        default:
          caEnabled: false
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-production
      enabled: true
```

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```
operator chart version - 0.3.24
redpanda chart version - 5.6.25
```

</details>

### Cloud provider

<details>
Linode
</details>

**Comment by alejandroEsc** [comment]
I believe this was fixed recently . Can you please include the helmrelease and the version indicated there?

**Comment by Aransh** [comment]
@alejandroEsc When I posted this issue, the operator was installing chart version 5.6.25
As of now, I see the operator tried to update to version 5.6.36, which seems to fail due to the same issue, just different error...
redpanda-console pod throwing error:
> {"level":"fatal","msg":"failed to validate config","error":"failed to validate Redpanda config: failed to validate admin api config: URL scheme is https (given URL: \"https://redpanda.redpanda.svc.cluster.local.:9644\"), but you have TLS disabled. Change URL scheme to http"}

2 things worth mentioning:
1. The error mentions I need to change the scheme, but since this is using the operator, I did not set the scheme myself, the operator did, so, operator bug?
2. The error says "you have TLS disabled", but as you can see in my redpanda yaml, I have (per documentation):

```
tls:
  enabled: true
```

**Comment by RafalKorepta** [comment]
Hi @Aransh 

There are multiple issues. 

# Seed server list and RPC listener

If you enable TLS on internal listener (internal to the Kubernetes cluster), then seed server list is miss configured as brokers try to talk to each other via the following DNS names
```
  seed_servers:
    - host:
        address: redpanda-0.redpanda.redpanda.svc.cluster.local.
        port: 33145
    - host:
        address: redpanda-1.redpanda.redpanda.svc.cluster.local.
        port: 33145
    - host:
        address: redpanda-2.redpanda.redpanda.svc.cluster.local.
        port: 33145
```

Each redpanda sends errors like:
```
ERROR 2023-10-31 11:39:20,492 [shard 0] rpc - Error dispatching client reads to {host: redpanda-2.redpanda.redpanda.svc.cluster.local., port: 33145}: std::runtime_error (error while extracting certificate DN strings)
```

Which means that certificate subject alternative name doesn't match kubernetes headless service naming convention. Which is ok, as you wanted to have certificate signed by let's encrypt (snippet of certificate):
```
Spec:
  Dns Names:
    perf-redpanda.linode.csi.akadns6.net
    *.perf-redpanda.linode.csi.akadns6.net
  Duration:  43800h0m0s
  Issuer Ref:
    Group:  cert-manager.io
    Kind:   ClusterIssuer
    Name:   letsencrypt-production
  Private Key:
    Algorithm:  ECDSA
    Size:       256
  Secret Name:  redpanda-default-cert
```

To change that behavior I see only one option to disable RPC listener tls option
```
spec:
  clusterSpec:
    listeners:
      rpc:
        tls:
          enabled: false
```

# Config watcher and Admin API

The config watcher a side car of all Redpanda pods have cluster health check https://github.com/redpanda-data/helm-charts/blob/b7d0f691ad9048592b9b5e954a3d3d821811fc40/charts/redpanda/templates/secrets.yaml#L179

That check relay on rpk configuration which is mounted to each Redpanda pods by `/etc/redpanda/redpanda.yaml` file.

This is the rpk configuration
```
rpk:
    kafka_api:
        brokers:
            - redpanda-0.redpanda.redpanda.svc.cluster.local.:9093
            - redpanda-1.redpanda.redpanda.svc.cluster.local.:9093
            - redpanda-2.redpanda.redpanda.svc.cluster.local.:9093
    admin_api:
        addresses:
            - redpanda-0.redpanda.redpanda.svc.cluster.local.:9644
            - redpanda-1.redpanda.redpanda.svc.cluster.local.:9644
            - redpanda-2.redpanda.redpanda.svc.cluster.local.:9644
    additional_start_flags:
        - --smp=1
        - --memory=2048M
        - --reserve-memory=205M
        - --default-log-level=info
    tune_aio_events: true
```

Unfortunately `admin_api` doesn't have tls configuration, so it is failing with the following error
```
kubectl logs redpanda-0 -c config-watcher -p
Waiting for cluster to be ready
Request error, trying another node: Get "http://redpanda-0.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02"
Request error, trying another node: Get "http://redpanda-2.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02"
unable to request cluster health: Get "http://redpanda-1.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02"
Error: (1) occurred at line 12
```

My internal test shows that even by adding rpk configuration to enable admin api tls configuration https://github.com/redpanda-data/helm-charts/blob/b7d0f691ad9048592b9b5e954a3d3d821811fc40/charts/redpanda/templates/_configmap.tpl#L545-L554

still the admin api DNS names doesn't match the domain. The config watcher with TLS enabled returns:

```
kubectl logs redpanda-0 -c config-watcher
Waiting for cluster to be ready
Request error, trying another node: Get "https://redpanda-2.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": tls: failed to verify certificate: x509: certificate is valid for perf-redpanda.linode.csi.akadns6.net, *.perf-redpanda.linode.csi.akadns6.net, not redpanda-2.redpanda.redpanda.svc.cluster.local.
Request error, trying another node: Get "https://redpanda-0.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": tls: failed to verify certificate: x509: certificate is valid for perf-redpanda.linode.csi.akadns6.net, *.perf-redpanda.linode.csi.akadns6.net, not redpanda-0.redpanda.redpanda.svc.cluster.local.
unable to request cluster health: Get "https://redpanda-1.redpanda.redpanda.svc.cluster.local.:9644/v1/cluster/health_overview": tls: failed to verify certificate: x509: certificate is valid for perf-redpanda.linode.csi.akadns6.net, *.perf-redpanda.linode.csi.akadns6.net, not redpanda-1.redpanda.redpanda.svc.cluster.local.
Error: (1) occurred at line 12
```

Because of that I would recommend to move `issuerRef` from `default` certificate to `external`. That way internally communication within kubernetes will be done using self sign certificate. External communication can be performed using Let's Encrypt certificate.

My test that passed
```
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    listeners: <----- THIS WAS ADDED TO DISABLE TLS INSIDE RPC
      rpc:
        tls:
          enabled: false
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-512
        secretRef: redpanda-superusers
        users: []
    external:
      domain: perf-redpanda.linode.csi.akadns6.net
      enabled: true
      externalDns:
        enabled: true
      type: LoadBalancer
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
    tls:
      certs:
        external:  <----- THIS CHANGED FROM default
          caEnabled: false
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-production
      enabled: true
```
