### ISSUE TITLE
redpanda: console's secret is always created

### ISSUE THREAD

**Issue by koooge** [redpanda-data/helm-charts#833]
### What happened?

Hi there, redpanda console's secret is always created in the latest.

### What did you expect to happen?

I expected console's secret is not created by default. In particular, I don't want to generate `login-jwt-secret` with a random value.

charts/redpanda/value.yaml:

```
console:
  enabled: true
  configmap:
    create: false
  secret:
    create: false # <= This does not work I think.
  deployment:
    create: false
  config: {}
```

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm template -f charts/redpanda/value.yaml charts/redpanda
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

- chart version : 5.6.33

### Cloud provider

<details>

</details>
