### ISSUE TITLE
Unable to configure tiered storage for Azure blob store

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#871]
### What happened?

Tried both of the following configs, but neither seem to set the cluster config values as expected:
```
storage:                                                                                                                                                                                                                                             
  tieredConfig:
    cloud_storage_enabled: true
    cloud_storage_azure_shared_key: mykey
    cloud_storage_azure_storage_account: jlpsa
    cloud_storage_azure_container: redpanda
```

And:
```
storage:                                                                                                                                                                                                                                        tiered:        
    config:   
      cloud_storage_enabled: true
      cloud_storage_azure_shared_key: mykey
      cloud_storage_azure_storage_account: jlpsa
      cloud_storage_azure_container: redpanda
```

### What did you expect to happen?

Running `rpk cluster config edit` and searching for `azure_` would show the values for each parameter as set in values.yaml.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

[helm-values-output.log](https://github.com/redpanda-data/helm-charts/files/13350806/helm-values-output.log)

</details>


### Anything else we need to know?

_No response_

### Which are the affected charts?

_No response_

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
redpanda        redpanda        1               2023-11-14 09:04:26.111284091 -0600 CST deployed        redpanda-5.6.44         v23.2.15
```

</details>


### Cloud provider

<details>

</details>
