### ISSUE TITLE
Unable to upgrade from v5.5.1 to latest

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/helm-charts#894]
### What happened?

The `values.yaml` format for the TLS settings doesn't appear to have changed since v5.5.1, but using the same `value.yaml` file with the latest Helm chart I am getting the follow error:

`
Error: template: redpanda/charts/redpanda/templates/configmap.yaml:41:16: executing "redpanda/charts/redpanda/templates/configmap.yaml" at <include "rpk-config-external" .>: error calling include: template: redpanda/charts/redpanda/templates/_configmap.tpl:600:16: executing "rpk-config-external" at <$cert.caEnabled>: can't evaluate field caEnabled in type string
`

`
helm.go:84: [debug] template: redpanda/charts/redpanda/templates/configmap.yaml:41:16: executing "redpanda/charts/redpanda/templates/configmap.yaml" at <include "rpk-config-external" .>: error calling include: template: redpanda/charts/redpanda/templates/_configmap.tpl:600:16: executing "rpk-config-external" at <$cert.caEnabled>: can't evaluate field caEnabled in type string
`

### What did you expect to happen?

The latest Helm chart to upgrade Redpanda from `v23.2.9` to `v23.2.16`.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Chart Version(s)

`v5.6.48`

### Cloud provider

Azure AKS

**Comment by jrkinley** [comment]
This was caused by missing configuration. `caEnabled: false` needed to be defined in both:

From:
```
  tls:
    enabled: false
    certs:
      default: ~
      external:
        secretRef:
          name: cert
        caEnabled: false
```

To:
```
  tls:
    enabled: false
    certs:
      default:
        caEnabled: false
      external:
        secretRef:
          name: cert
        caEnabled: false
```
