### ISSUE TITLE
Setting redpanda console values does not properly merge defaults 

### ISSUE THREAD

**Issue by WesWWagner** [redpanda-data/helm-charts#896]
### What happened?

When attempting to enable SSL for redpanda console as part of an embedded console helm deployment, the default values needed to properly stgart the pod are not merged.
Example: 

```
helm install redpanda redpanda/redpanda \
  --namespace arkoserp --create-namespace \
  --set auth.sasl.enabled=true \
  --set "auth.sasl.users[0].name=superuser" \
  --set "auth.sasl.users[0].password=secretpassword" \
  --set external.domain=${DOMAIN} \
  --set "storage.persistentVolume.storageClass=csi-driver-lvm-striped-xfs" \
  --set console.console.config.server.tls.enabled=true \
  --wait \
  --timeout 1h
```

results in:
`Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment.apps "redpanda-console" is invalid: spec.template.spec.containers[0].ports[0].containerPort: Required value`
	

### What did you expect to happen?

In theory all defaults should be still merged and likely result in a different error, like for example me not setting the CA path because that is not part of the general defaults.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Run the above helm command as a template command instead and observe the blank containerPort line under console.

```
      containers:
        - name: console
          command: ["sh","-c","set -e; IFS=':' read -r KAFKA_SASL_USERNAME KAFKA_SASL_PASSWORD KAFKA_SASL_MECHANISM \u003c \u003c(grep \"\" $(find /mnt/users/* -print)); KAFKA_SASL_MECHANISM=${KAFKA_SASL_MECHANISM:-SCRAM-SHA-512}; export KAFKA_SASL_USERNAME KAFKA_SASL_PASSWORD KAFKA_SASL_MECHANISM;  export KAFKA_SCHEMAREGISTRY_USERNAME=$KAFKA_SASL_USERNAME;  export KAFKA_SCHEMAREGISTRY_PASSWORD=$KAFKA_SASL_PASSWORD;  /app/console $@","--"]
          args:
            - "--config.filepath=/etc/console/configs/config.yaml"
          securityContext:
            runAsNonRoot: true
          image: docker.redpanda.com/redpandadata/console:v2.3.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort:
              protocol: TCP
```

### Anything else we need to know?

@RafalKorepta may have additional background since he has been looking at it.

### Which are the affected charts?

Console

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART          	APP VERSION
redpanda	arkoserp 	1       	2023-11-27 09:50:16.355041 -0800 PST	deployed	redpanda-5.6.49	v23.2.17

### Cloud provider

<details>
Amazon EKS default cluster install per docs.redpanda.com
</details>
