### ISSUE TITLE
Better support for managing audit topic with the Topic resource

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#955]
### What would you like to be added?

It would be nice to have an option in the Helm chart `auditLogging` config to create a Topic resource for the audit topic (`_redpanda.audit_log`).

### Why is this needed?

It's currently a convoluted series of steps to get this working:

1. Deploy the Redpanda resource with SASL auth enabled
    ```yaml
    apiVersion: cluster.redpanda.com/v1alpha1
    kind: Redpanda
    metadata:
      name: redpanda
    spec:
      chartRef: {}
      clusterSpec:
        auth:
          sasl:
            enabled: true
    ```
2. Create a separate Secret to hold the password of a superuser/user. We need this because the Topic resource requires a Secret that has only the password under a specific `key`.
    ```
     kubectl create secret generic my-secret --from-literal=password=<password> -n redpanda
    ```
3. Deploy a Topic resource and name it `_redpanda.audit_log`
    ```yaml
    apiVersion: cluster.redpanda.com/v1alpha1
    kind: Topic
    metadata:
      name: audit-topic
    spec:
      partitions: 3
      replicationFactor: 1
      overwriteTopicName: _redpanda.audit_log
      kafkaApiSpec:
        brokers:
          - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
          - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
          - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
        tls:
          caCertSecretRef:
            name: "redpanda-default-cert"
            key: "ca.crt"
        sasl:
          username: jake
          mechanism: SCRAM-SHA-256
          passwordSecretRef:
            name: my-secret
            key: password
    ```
4. Enable audit logging and make sure to set the replication factor and partition configs to the same values as the ones you used when you created the topic. These values cannot be changed. So if they don't match, you see errors like `Topic":{"name":"audit-topic","namespace":"redpanda"},"namespace":"redpanda","name":"audit-topic","reconcileID":"d23c9d86-5096-4aeb-bb07-1c6bdb2b2adc","error":"alter topic configuration (_redpanda.audit_log) incremental alter config (none): TOPIC_AUTHORIZATION_FAILED: Not authorized to access topics: [Topic authorization failed.]"}`
    ```yaml
    apiVersion: cluster.redpanda.com/v1alpha1
    kind: Redpanda
    metadata:
      name: redpanda
    spec:
      chartRef: {}
      clusterSpec:
        auth:
          sasl:
            enabled: true
        auditLogging:
          enabled: true
    ```

**Comment by RafalKorepta** [comment]
Users can always create super user credentials before Redpanda and Topic custom resource.

```bash
kubectl create secret generic redpanda-superusers --from-literal=superusers.txt='<superuser-name>:<superuser-password>:<superuser-authentication-mechanism>'
kubectl create secret generic my-secret --from-literal=password=<superuser-password> -n redpanda
```

```yaml
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    auth:
      sasl:
        enabled: true
        secretRef: "redpanda-superusers"
        users: []
     auditLogging:
      enabled: true
```

```yaml
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: audit-topic
spec:
  partitions: 3
  replicationFactor: 1
  overwriteTopicName: _redpanda.audit_log
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
    sasl:
      username: <superuser-name>
      mechanism: <superuser-authentication-mechanism>
      passwordSecretRef:
        name: my-secret
        key: password
```

The best option would be to implement https://github.com/redpanda-data/redpanda-operator/issues/46. That way Topic would not need brokers, sasl nor tls configuration only Redpanda reference.
