### ISSUE TITLE
Connectors extraEnv values not applying if sasl is enabled

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#959]
### What happened?

Similar to https://github.com/redpanda-data/helm-charts/issues/940 (handled by @alejandroEsc ).
If "auth.sasl.enabled" is true, then values added via "connectors.deployment.extraEnv" will not be applied.
Once sasl is disabled, all is working.

### What did you expect to happen?

I expected the additional set env var to be applied

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>
Minimal Helm values for the redpanda chart, that doesn't add my env var:

```
auth:
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    secretRef: kafka-credentials
    users: []
connectors:
  deployment:
    extraEnv:
      - name: REDPANDA_PLUGINS_TARGET_DIR
        value: /opt/kafka/connect-plugins
  enabled: true
```

Minimal Helm values for the redpanda chart, that does add my env var:

```
auth:
  sasl:
    enabled: false
    mechanism: SCRAM-SHA-512
    secretRef: kafka-credentials
    users: []
connectors:
  deployment:
    extraEnv:
      - name: REDPANDA_PLUGINS_TARGET_DIR
        value: /opt/kafka/connect-plugins
  enabled: true
```
</details>

### Anything else we need to know?

I am using the operator, but it is unrelated as I've been able to replicate this using pure "helm template" commands as such:
helm template redpanda/redpanda -f values.yaml

### Which are the affected charts?

Redpanda, Connectors

### Chart Version(s)

<details>

```console
redpanda chart version 5.7.5
```

</details>

### Cloud provider

<details>
Linode
</details>
