### ISSUE TITLE
Redpanda Pods CrashBackLoop with Default TLS Configuration

### ISSUE THREAD

**Issue by pgb6** [redpanda-data/helm-charts#961]
### What happened?

Slack thread for context: https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1703271402195649

I'm not certain this is tied to any of the upgraded CRDs/Charts, but it is likely -- specifying the following TLS configuration in my Redpanda CRD caused the redpanda cluster to fail to start and achieve a healthy state:
```
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    tls:
      enabled: true
      certs:
        kafka-root-certificate:
          secretRef:
            name: kafka-root-certificate
          caEnabled: true
        default: 
          caEnabled: true
    auth:
      sasl:
        enabled: true
        secretRef: redpanda-superusers
        users: []
    listeners:
      admin:
        port: 9644
        tls:
          cert: default
          enabled: true
      kafka:
        authenticationMethod: sasl
        port: 9092
        tls:
          cert: kafka-root-certificate
          enabled: true
      rpc:
        port: 33145
    logging:
      logLevel: trace
      usageStats:
        enabled: false
    resources:
      cpu:
        cores: "4"
      memory:
        enable_memory_locking: true
        container:
          max: 10G
    statefulset:
      replicas: 3
    storage:
      persistentVolume:
        enabled: true
        size: 100Gi
```
Specifically, the default certificate that was used for the admin API was causing instability when making an admin API calls. This thwarted the readiness check for all the redpanda pods, thus causing `crashbackoffloops`. Removing the default certificate configuration like so fixed this:
```
```
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    tls:
      enabled: true
      certs:
        kafka-root-certificate:
          secretRef:
            name: kafka-root-certificate
          caEnabled: true
    auth:
      sasl:
        enabled: true
        secretRef: redpanda-superusers
        users: []
    listeners:
      admin:
        port: 9644
        tls:
          enabled: true
      kafka:
        authenticationMethod: sasl
        port: 9092
        tls:
          cert: kafka-root-certificate
          enabled: true
      rpc:
        port: 33145
    logging:
      logLevel: trace
      usageStats:
        enabled: false
    resources:
      cpu:
        cores: "4"
      memory:
        enable_memory_locking: true
        container:
          max: 10G
    statefulset:
      replicas: 3
    storage:
      persistentVolume:
        enabled: true
        size: 100Gi
```
```

### What did you expect to happen?

For the redpanda cluster to spin up healthily. 

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

See the cluster spec provided in the context above.

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
redpanda-5.7.5
```

```
app version v23.3.1
```

</details>

### Cloud provider

<details>
AWS
</details>
