### ISSUE TITLE
tiered-storage credentials access key from secretRef

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#981]
### What happened?

Following up on https://github.com/redpanda-data/helm-charts/issues/960, I am looking for the tiered-storage access key to also be read from a secretRef.

### What did you expect to happen?

Our current flow is:
1. Create access key and push it to secret manager (via terraform)
2. Use operator to create k8s secrets from secret manager secrets
3. Use secretRefs to point to the pre-existing secrets

This is not so fluid considering the access key needs to be set manually in the value currently.
I would expect to replace this:

```
      tiered:
        config:
          cloud_storage_access_key: xxxx
        credentialsSecretRef:
          name: redpanda-tiered-storage-secret
          key: SECRET_KEY
```

With perhaps something like this:
```
      tiered:
        credentialsSecretRef:
          accessKey:
            name: redpanda-tiered-storage-secret
            key: ACCESS_KEY
          secretKey:
            name: redpanda-tiered-storage-secret
            key: SECRET_KEY
```

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Nothing to reproduce

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```console
redpanda-5.7.9
```

</details>

### Cloud provider

<details>
Linode
</details>
